Added placeholder images if none defined
ONSdigital/design-system pull request #1187
Opened 2020-11-24 15:28 UTC by trevorsaint

**Updated articles to include:**

- height and width property on image tag
- css max-width property on image container
- placeholder image fallbacks for featured and general articles if none specified

Image dimensions are included in the documentation and should be added into Craft as **image modifiers**. This will ensure the correct image size is used,  even if full-scale resolution images are added by the client.

2020-11-24 16:27 UTC, rmccar requested changes
Other than these two suggestions looks good

2020-11-24 16:27 UTC, rmccar commented on src/components/articles/_macro.njk
> +                                {% if article.image is defined and article.image and article.image.filename %}
```suggestion
                                {% if article.image is defined and article.image and article.image.filename is defined and article.image.filename %}
```

2020-11-24 16:27 UTC, rmccar commented on src/components/articles/_macro.njk
> +                                {% if article.image is defined and article.image and article.image.filename %}
```suggestion
                                {% if article.image is defined and article.image and article.image.filename is defined and article.image.filename %}
```

2020-11-25 14:02 UTC, boxadesign approved these changes

2020-11-25 14:31 UTC, rmccar approved these changes

2020-11-25 17:22 UTC, merged