Can't add classes to feedback div and border doesn't match the default header theme colour
ONSdigital/design-system pull request #1508
Opened 2021-05-07 15:10 UTC by jrbarnes9

### What is the context of this PR?
The feedback component was only built for census.  So this PR allows support for the ONS default brand and expanded the colours variables to enable this.
Also added ability to add classes to the feedback container which will allow more control of spacing with utility classes.

### How to review
Check the feedback component and colour variables

2021-05-10 09:51 UTC, boxadesign requested changes

2021-05-10 09:51 UTC, boxadesign commented on package.json
> +    "node-sass": "4.14"
Need to move this back to `devDependencies`

2021-05-10 09:52 UTC, boxadesign commented
![image](https://user-images.githubusercontent.com/1015442/117641130-b889d080-b17d-11eb-8f71-44c189c1c160.png)

Think the default bg change or hero needs a tweak.

2021-05-10 12:09 UTC, boxadesign commented
Still need to move `node-sass` into `devDependencies`

2021-05-14 15:10 UTC, rmccar approved these changes

2021-05-17 11:23 UTC, boxadesign approved these changes

2021-05-17 12:04 UTC, merged