1546 duration use
ONSdigital/design-system pull request #1551
Opened 2021-06-14 08:06 UTC by JNATION85

Durations example uses min and max attributes which are invalid for text inputs

2021-06-14 11:12 UTC, jrbarnes9 approved these changes

2021-06-14 15:39 UTC, jrbarnes9 requested changes
Also needs removing from the mutually exclusive duration example: https://ons-design-system.netlify.app/components/mutually-exclusive/examples/duration/

2021-06-15 07:03 UTC, JNATION85 reviewed
Pushed changes

2021-06-15 07:49 UTC, rmccar commented on src/components/mutually-exclusive/examples/duration/index.njk
> +            "name": "address-duration-years"
```suggestion
            "name": "address-duration-years",
            "label": "Years"
```

2021-06-15 07:49 UTC, rmccar commented on src/components/mutually-exclusive/examples/duration/index.njk
> +            "name": "address-duration-months"
```suggestion
            "name": "address-duration-months",
            "label": "Months"
```

2021-06-15 07:49 UTC, rmccar commented on src/components/mutually-exclusive/examples/duration/index.njk
> +            "name": "address-duration-months"
These two labels need to be added back in. Other than that looks good!

2021-06-16 12:27 UTC, jrbarnes9 approved these changes

2021-06-17 11:42 UTC, rmccar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #1546: Durations example uses `min` and `max` attributes which are invalid for `text` inputs](https://trello.com/c/G8oNTmj8/1194-issue-1546-durations-example-uses-min-and-max-attributes-which-are-invalid-for-text-inputs)

2021-06-17 11:42 UTC, merged