Add buttonContext to docs and fix indenting
ONSdigital/design-system pull request #1558
Opened 2021-06-16 07:48 UTC by rmccar

### What is the context of this PR?
Adds the buttonContext param to the docs for buttons.
Also updates the button macro indentation to bring it inline with other macros

### How to review
Check docs make sense for buttonContext

2021-06-16 07:49 UTC, rmccar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Param.buttoncontext missing from button params docs](https://trello.com/c/aSl5aDEA/573-parambuttoncontext-missing-from-button-params-docs)

2021-06-17 08:31 UTC, jrbarnes9 requested changes

2021-06-17 08:31 UTC, jrbarnes9 commented on src/components/button/_macro-options.md
> +| buttonContext | string            | false    | Used for collapsibles, a string of text hidden but read out by screenreaders to describe which part of the collapsible is the content
```suggestion
| buttonContext | string            | false    | Can be used to add context to a button’s `text` label, for screen readers. For example, the “Hide this” button in the collapsible component, requires context to let a screen reader user to know what the button hides |
```

2021-06-17 13:34 UTC, jrbarnes9 commented on src/components/button/_macro-options.md
> +| buttonContext | string            | false    | Can be used to add context to a button’s `text` label, for screen readers. For example, the “Hide this” button in the collapsible component, requires
```suggestion
| buttonContext | string            | false    | Can be used to add context to a button’s `text` label, for screen readers. For example, the “Hide this” button in the collapsible component requires context to help let a screen reader user know what the button hides. |
```

2021-06-18 08:17 UTC, jrbarnes9 approved these changes

2021-06-18 12:27 UTC, boxadesign approved these changes

2021-06-18 14:04 UTC, merged