Design System - Document ways of consuming the DS
ONSdigital/design-system pull request #1576
Opened 2021-06-25 11:39 UTC by boxadesign

### What is the context of this PR?
Created a new set of pages under /get-started

2021-06-29 10:25 UTC, rmccar approved these changes

2021-07-09 07:43 UTC, jrbarnes9 commented
Think we need something on the top level "Get started" page to introduce the installation pages
<details><summary>Browser metadata</summary>





```
Path:      /get-started/
Browser:   Chrome 91.0.4472.106 on Mac OS 10.14.6
Viewport:  1280 x 698 @2x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-1576--ons-design-system.netlify.app%2Fget-started%2F&os=OS+X&os_version=Mojave&browser=Chrome&browser_version=91.0&resolution=1280x698&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-1576--ons-design-system.netlify.app/get-started/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60e5a9c336b60b0008207b6a&commentID=60e7fe2770d6da85b59f951a&resolution=resolved)

2021-07-09 07:46 UTC, jrbarnes9 commented
Maybe we shouldn't spell out CSS in the heading, because it's not great for a nav item when the devs will be looking for "CSS"
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNzc0N2FkYzgtYzY1MC00ODNkLWI1YTEtZDgzMDAzZjQ2MjAxIiwiZGVwbG95X2lkIjoiNjBlNWE5YzMzNmI2MGIwMDA4MjA3YjZhIiwiaWQiOiJiNDBlMjlkZi00N2JmLTQwMDAtYjE0Yi02NDYyNjAyOGZiM2MifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /get-started/css-js-assets/
Browser:   Chrome 91.0.4472.106 on Mac OS 10.14.6
Viewport:  1280 x 698 @2x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-1576--ons-design-system.netlify.app%2Fget-started%2Fcss-js-assets%2F&os=OS+X&os_version=Mojave&browser=Chrome&browser_version=91.0&resolution=1280x698&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-1576--ons-design-system.netlify.app/get-started/css-js-assets/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60e5a9c336b60b0008207b6a&commentID=60e7fecd922616820a1aeab7&resolution=resolved)

2021-07-09 07:50 UTC, jrbarnes9 commented
Don't think it makes sense to spell it out here either.  There's also a broken link in the last bullet point.
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNzc0N2FkYzgtYzY1MC00ODNkLWI1YTEtZDgzMDAzZjQ2MjAxIiwiZGVwbG95X2lkIjoiNjBlNWE5YzMzNmI2MGIwMDA4MjA3YjZhIiwiaWQiOiIxMDkyNzJiOC03MWY5LTRhM2YtYWZiMy0xNTFkOThiZTJlYzQifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /get-started/npm/
Browser:   Chrome 91.0.4472.106 on Mac OS 10.14.6
Viewport:  1280 x 698 @2x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-1576--ons-design-system.netlify.app%2Fget-started%2Fnpm%2F&os=OS+X&os_version=Mojave&browser=Chrome&browser_version=91.0&resolution=1280x698&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-1576--ons-design-system.netlify.app/get-started/npm/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60e5a9c336b60b0008207b6a&commentID=60e7ffd492261684731aeb03&resolution=resolved)

2021-07-09 08:07 UTC, jrbarnes9 commented
I don't think Markdown likes tags written in the `` markdown so probably need to use `<code>`
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNzc0N2FkYzgtYzY1MC00ODNkLWI1YTEtZDgzMDAzZjQ2MjAxIiwiZGVwbG95X2lkIjoiNjBlNWE5YzMzNmI2MGIwMDA4MjA3YjZhIiwiaWQiOiI5MmZkNTlhZC1hM2MzLTQ5MWEtYWRkMS1hNDQyNzc1OGFmNWIifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /get-started/css-js-assets/#cdn
Browser:   Chrome 91.0.4472.106 on Mac OS 10.14.6
Viewport:  1280 x 698 @2x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-1576--ons-design-system.netlify.app%2Fget-started%2Fcss-js-assets%2F%23cdn&os=OS+X&os_version=Mojave&browser=Chrome&browser_version=91.0&resolution=1280x698&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-1576--ons-design-system.netlify.app/get-started/css-js-assets/#cdn) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60e5a9c336b60b0008207b6a&commentID=60e803b8aa49478357674dd0&resolution=resolved)

2021-07-09 08:11 UTC, jrbarnes9 commented on src/get-started/css-js-assets/index.njk
> +{{ onsCodeHighlight({ "code": "@import 'node_modules/@ons/design-system/components/button/button';" }) }}
Just checking `/button/button` is correct and not a typo?

2021-07-14 10:03 UTC, boxadesign commented
> **A reviewer left a comment:**
> 
> Exporting SVGs and Browser compatibility pages need updating to new content in Google docs
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-1576--ons-design-system.netlify.app/get-started/browser-compatibility/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60e5a9c336b60b0008207b6a&commentID=60e80cb780ba80a27a0b3596&resolution=resolved)

This won't be done in this PR.

2021-07-14 10:03 UTC, boxadesign commented
> **A reviewer left a comment:**
> 
> Design assets:
> Can you change the first two paras so they match what's in the Google doc:
> We use Sketch to mock up designs and create click-through prototypes to demonstrate user journeys and carry out user testing.
> First, download Sketch to your device. You then need the ONS Sketch Library to create designs and prototypes that are consistent with our brand and styles.
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-1576--ons-design-system.netlify.app/get-started/design-assets/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60e5a9c336b60b0008207b6a&commentID=60e80c38423fcc920cea64d4&resolution=resolved)

This won't be done in this pr

2021-07-14 15:39 UTC, jrbarnes9 commented
`<head>` tag still not rendering 
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNzc0N2FkYzgtYzY1MC00ODNkLWI1YTEtZDgzMDAzZjQ2MjAxIiwiZGVwbG95X2lkIjoiNjBlZWU5NjMwMTVhMTIwMDA3ZTUxMGJiIiwiaWQiOiI4ZDljOTkzMC02YjY5LTRjMGUtYjQyYi1kNjJiMDI4MGY0OGUifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /get-started/css-js-assets/
Browser:   Chrome 91.0.4472.106 on Mac OS 10.14.6
Viewport:  1920 x 978 @1x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-1576--ons-design-system.netlify.app%2Fget-started%2Fcss-js-assets%2F&os=OS+X&os_version=Mojave&browser=Chrome&browser_version=91.0&resolution=1920x978&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-1576--ons-design-system.netlify.app/get-started/css-js-assets/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60eee963015a120007e510bb&commentID=60ef051c162c135c45702e5b&resolution=resolved)

2021-07-14 15:50 UTC, jrbarnes9 commented on src/get-started/npm/index.njk
> +- **base [page template](styles/page-template)** – a Nunjucks template that contains the core markup and components needed to create an ONS service.
```suggestion
- **base [page template](/styles/page-template)** – a Nunjucks template that contains the core markup and components needed to create an ONS service.
```

2021-07-16 09:22 UTC, jrbarnes9 submitted a review, later dismissed

2021-07-16 10:37 UTC, LauraC119 reviewed
Using the CSS, JS and assets page:
1. Change the note you've added to:
Note that some local development environments require you to override the the global ONS_assets_base_URL variable to use the chunked JS files. To do this, add the following script before the reference to the main.js file:
2. Change the two "you're"s to "you are"

Install NPM page:
1. change "Compiled" on the bullet list to lower case
2. remove full stop on the end of the bullet list

2021-07-16 11:00 UTC, jrbarnes9 approved these changes

2021-07-16 11:16 UTC, LauraC119 requested changes
So sorry, I made a mistake in that new paragraph. Can you remove the duplicated "the":
"require you to override the **the** global ONS_assets_base_URL variable"

2021-07-16 12:06 UTC, LauraC119 approved these changes

2021-07-16 12:15 UTC, jrbarnes9 approved these changes

2021-07-16 12:16 UTC, merged