New feature proposal documentation
ONSdigital/design-system pull request #1580
Opened 2021-06-30 15:28 UTC by jrbarnes9

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review
Describe the steps required to test the changes (include screenshots if appropriate).

2021-07-08 14:31 UTC, jrbarnes9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [How to propose a new feature](https://trello.com/c/elhlgc95/1226-how-to-propose-a-new-feature)

2021-07-08 14:32 UTC, jrbarnes9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [How to propose a change](https://trello.com/c/4JI7BkeJ/1227-how-to-propose-a-change)

2021-07-12 08:18 UTC, rmccar requested changes

2021-07-12 08:18 UTC, rmccar commented on src/contribute/propose-a-change/index.njk
> +{% from "components/external-link/_macro.njk" import onsExternalLink %}
```suggestion
```

Imported external link twice

2021-07-12 08:18 UTC, rmccar commented on src/contribute/propose-a-new-feature/index.njk
> +{% from "components/external-link/_macro.njk" import onsExternalLink %}
```suggestion
```

Imported external link twice

2021-07-12 08:18 UTC, rmccar commented on src/contribute/propose-a-new-feature/index.njk
> +                "text": 'being developed – you can check this on the <a class="external-link" target="_blank" rel="noopener" href="https://github.com/ONSdigital/design-system/projects/1">community ba
External link not styled correctly

2021-07-13 07:34 UTC, rmccar approved these changes

2021-07-13 13:45 UTC, LauraC119 approved these changes

2021-07-14 13:46 UTC, merged