Add service links to example and fix style
ONSdigital/design-system pull request #1616
Opened 2021-07-30 10:40 UTC by rmccar

### What is the context of this PR?
Fixes: #1577
Also updated docs and header title param to conform with navigation links **(BREAKING CHANGE)**

### How to review
Example now looks as expected

2021-07-30 10:40 UTC, rmccar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #1577: Service Links missing from internal header example and incorrectly styled when applied](https://trello.com/c/dgMpxFvF/1235-issue-1577-service-links-missing-from-internal-header-example-and-incorrectly-styled-when-applied)

2021-07-30 11:39 UTC, jrbarnes9 requested changes
Can we also add `currentPath` to the census header examples?

2021-07-30 11:39 UTC, jrbarnes9 commented on src/components/header/examples/internal-basic/index.njk
> +                    "title": "Styles",
```suggestion
                    "title": "Sign out",
```

2021-07-30 11:39 UTC, jrbarnes9 commented on src/components/header/_header.scss
> +    }
I think the hover style for these links should match other white on colour links, same as the [promo banner](https://ons-design-system.netlify.app/components/promotional-banner/) and [announcement panel](https://ons-design-system.netlify.app/components/panel/examples/announcement/),  for example.

2021-08-02 10:14 UTC, boxadesign approved these changes

2021-08-09 07:04 UTC, jrbarnes9 approved these changes

2021-08-09 09:23 UTC, boxadesign approved these changes

2021-08-12 09:38 UTC, jrbarnes9 approved these changes

2021-08-12 12:06 UTC, merged