Design System - Updated docs for using scripts via npm
ONSdigital/design-system pull request #1627
Opened 2021-08-10 12:35 UTC by boxadesign

### What is the context of this PR?
Updated documentation for using JS.

Found here -> /get-started/css-js-assets/#javascript

### How to review
Check the docs.

2021-08-11 09:22 UTC, LauraC119 submitted a review, later dismissed
1. Header – add the acronym - "JavaScript (JS)" - and then use it after that as we use the acronym in following section on CDN

2. After the header, change every "Javascript" to "JS"

3. "- add JavaScript file to your HTML - import JavaScript using a bundler" – I assume these will be bullet points when formatted correctly?

4. Webpack link not found

5. Change
"Import the node_modules/design-system/js/main.js which will import JavaScript for all components."
to
"Import node_modules/design-system/js/main.js to import the JS for all components."

6. Change 
"To import the JavaScript for a specific component, for instance the button component. You can import node_modules/design-system/components/button/button.dom.js." 
to
"You can import the JS for a specific component. For example, node_modules/design-system/components/button/button.dom.js imports the JS for the button component."

7. Change
"to import which will handle initialising a component."
to
"to import. This file will handle the initialising of a component."

2021-09-09 12:14 UTC, jrbarnes9 requested changes
Code blocks should be inline to better deal with wrapping 
![Screenshot_20210909-130744](https://user-images.githubusercontent.com/43346934/132683506-269c99e6-b26f-48ca-9272-0bec522f5179.png)

2021-09-09 12:14 UTC, jrbarnes9 commented on src/pages/get-started/css-js-assets/index.njk
> +You can import the JS for a specific component. For example, `node_modules/design-system/components/button/button.dom.js` imports the JS for the button component. Each component that uses JS will hav
```suggestion
You can import the JS for a specific component. For example, `node_modules/design-system/components/button/button.dom.js` imports the JS for the button component. Each component that uses JS will have a `<COMPONENT>.dom.js` file available to import. This file will handle the initialising of a component.
```

2021-09-09 13:02 UTC, rmccar requested changes
Javascript navigation link is broken. ID of the Javascript h2 element is "javascript-js" and the link is looking for "#javascript"

2021-09-09 14:14 UTC, jrbarnes9 approved these changes

2021-09-09 14:22 UTC, rmccar approved these changes

2021-09-10 09:29 UTC, merged