Update published research content
ONSdigital/design-system pull request #1629
Opened 2021-08-11 07:28 UTC by jrbarnes9

### What is the context of this PR?
- Updated the UR findings previously published for:
  - input
  - feedback
  - relationships
  - textarea
  - addresses

### How to review
Check the docs

2021-08-11 07:45 UTC, jrbarnes9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update published research content](https://trello.com/c/gEg3jAD6/1275-update-published-research-content)

2021-08-11 09:42 UTC, LauraC119 commented
> **A reviewer left a comment:**
> 
> Textarea, Research on this pattern:
> If we're talking about us preferring the limit (which I think we are), change this bullet point:
> "limiting the characters that can be entered is preferred as it prevents users entering far more text than is needed"
> to
> "it is best to limit the characters that can be entered as this stops users entering far more text than is needed"
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-1629--ons-design-system.netlify.app/components/textarea/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61137fc0ae6c6e00076435c3&commentID=611384591ef7f4ac72359193&resolution=resolved)

2021-08-12 10:02 UTC, LauraC119 requested changes
On Addresses, the last bullet point. It's not clear that it's an instruction for user of the DS to do something to help their users

Change
this should be changed to add “name” to the the input label: “Enter name, address or postcode and select from results”
to
add “name” to the the input label when it's relevant so users know they can use this to search: “Enter name, address or postcode and select from results”

2021-08-12 13:28 UTC, LauraC119 approved these changes

2021-08-12 15:04 UTC, rmccar approved these changes

2021-08-12 15:54 UTC, merged