Namespace classes
ONSdigital/design-system pull request #1638
Opened 2021-08-13 10:20 UTC by boxadesign

### What is the context of this PR?
Namespace all css classes by prefixing `ons-`

### How to review
Describe the steps required to test the changes (include screenshots if appropriate).

2021-08-18 09:45 UTC, jrbarnes9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Namespace styles across DS](https://trello.com/c/GrgWL7Xn/1209-namespace-styles-across-ds)

2021-08-20 14:59 UTC, jrbarnes9 reviewed
Sub navigation anchor links are missing their dashed prefix.  (assuming this is inherited from the rebuild PR, but I can't check that because the netlify build is failing)
![Screenshot 2021-08-20 at 15 57 10](https://user-images.githubusercontent.com/43346934/130253082-56eea924-373c-4b4a-afe1-85f92789c336.png)

2021-08-20 15:03 UTC, jrbarnes9 commented
Broken link
![Screenshot 2021-08-20 at 16 03 08](https://user-images.githubusercontent.com/43346934/130253615-99d3b048-2e8a-4346-90a7-b4a9f1b5e39a.png)

2021-08-23 12:07 UTC, jrbarnes9 requested changes
- The classes in the Typography type scale table in need updating.
- In `src/components/input/_macro.njk` line 129 ` js-input-legend` missing prefix
- In `src/components/field/_field.scss` line 16, `field__item--w-{x}` missing prefix
- In `src/components/input/_macro.njk` line 97 and `src/components/search/_macro.njk` line 13, there's a typo `attribues` and `params.searchButton.attribues`
- In `src/components/download-resources/download-resources.js`: 
    - lines 1020 & 1064, `adv-filter__panel...` are missing prefix,
    - lines 550, 553, 647, 690, 738 & 741 `u-hidden` missing prefix
    - line 1064 `adv-filter__...` missing prefix
    - line 1054 `no-scroll` missing prefix
    - lines 320/321 `js-filter___...` missing prefix
- In `src/components/accordion/examples/accordion/index.njk` hardcoded classes in accordion `content` params are missing prefixes
- In all `onsButton` examples` the `classes` params are missing prefix
- Lots of component examples the use single quotes or the `classes` param value are missing prefix

2021-08-23 12:11 UTC, jrbarnes9 commented
- In `src/components/question/examples/question-ccs/index.njk`, line 25, `highlight` class missing prefix
- In `src/components/question/examples/question-interviewer-note/index.njk`, line 25, `instruction` class missing prefix

2021-08-23 12:18 UTC, jrbarnes9 reviewed
- In `src/components/tabs/tabs.js` line 143, `.tab...` class missing prefix

2021-09-02 13:25 UTC, jrbarnes9 requested changes
Just headings example in typography still missing the prefixes
![Screenshot 2021-09-02 at 09 39 45](https://user-images.githubusercontent.com/43346934/131851584-4856ea4d-3498-4634-a5b9-4ea341c35617.png)

2021-09-08 12:08 UTC, rmccar reviewed
![image](https://user-images.githubusercontent.com/42928680/132506595-d47138a2-6c73-4263-85b5-0da4c11cfdf5.png)
The Facebook icon might need looking at

2021-09-08 12:12 UTC, rmccar reviewed
![image](https://user-images.githubusercontent.com/42928680/132507080-2cf6c1ea-c19a-47b5-9fe0-0bf1ab233a78.png)
`ons-` missing from these classes

2021-09-08 12:14 UTC, rmccar reviewed
Also on the grid page some classes listed start with full stops and some don't. Should probably have all or nothing

2021-09-08 12:16 UTC, rmccar reviewed
![image](https://user-images.githubusercontent.com/42928680/132507610-3af7d9a1-ea22-4724-afd8-530c0c1c6c74.png)
Arabic example no longer right aligned

2021-09-08 12:18 UTC, rmccar requested changes
![image](https://user-images.githubusercontent.com/42928680/132507856-cbfd8672-4efc-4353-80e1-82616b05984e.png)
Facebook icon needs looking at

2021-09-08 12:20 UTC, rmccar commented
> ![image](https://user-images.githubusercontent.com/42928680/132507856-cbfd8672-4efc-4353-80e1-82616b05984e.png)
> Facebook icon needs looking at

Accidentally added this twice

2021-09-08 13:10 UTC, rmccar commented
![image](https://user-images.githubusercontent.com/42928680/132515423-de6b5dd0-6481-4bb6-a1aa-833e7f3a0212.png)
Needs `.ons-`

2021-09-08 13:14 UTC, rmccar commented
![image](https://user-images.githubusercontent.com/42928680/132515931-53f78d82-19d6-41b8-b803-f3f046594a04.png)
Collapsible accessibility docs need `ons-`

2021-09-08 13:19 UTC, rmccar commented
![image](https://user-images.githubusercontent.com/42928680/132516621-700a923f-096c-4a00-bcd3-8f72d45859aa.png)
Either `.ons-` needs to be added or docs need updating to say to add a description param not a class. I think the latter is better

2021-09-08 13:21 UTC, rmccar commented
![image](https://user-images.githubusercontent.com/42928680/132517216-81367d07-498c-4344-be78-4b00b9fa45ef.png)
Current page in pagination is no longer highlighted

2021-09-08 13:22 UTC, rmccar commented
![image](https://user-images.githubusercontent.com/42928680/132517366-329661f2-8519-4aeb-8bfd-43228fdf73e0.png)
Warning panel spacing is off

2021-09-08 13:27 UTC, rmccar commented
Status component needs `ons-` added to all classes

2021-09-08 13:31 UTC, rmccar commented
![image](https://user-images.githubusercontent.com/42928680/132518719-d21f9b27-9df9-4c66-9a32-6ee168d70c11.png)
`.ons-` needed to be added to summary docs

2021-09-08 13:33 UTC, jrbarnes9 commented
![image](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNzc0N2FkYzgtYzY1MC00ODNkLWI1YTEtZDgzMDAzZjQ2MjAxIiwiZGVwbG95X2lkIjoiNjEzOGI3ZTI1YzBiY2UwMDA3MGMwNGU0IiwiaWQiOiIxNzM1ZjUzMC02Njg0LTQ1MmUtYjRkNS00MjM0OTUyMjM5YTcifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /components/radios/
Browser:   Chrome 92.0.4515.159 on Mac OS 10.14.6
Viewport:  1331 x 794 @1x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1638--ons-design-system.netlify.app%2Fcomponents%2Fradios%2F&os=OS%20X&os_version=Mojave&browser=Chrome&browser_version=92.0&resolution=1331x794&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1638--ons-design-system.netlify.app/components/radios/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6138b7e25c0bce00070c04e4&commentID=6138bb8c73233dc8187649f2&resolution=resolved)

2021-09-08 13:34 UTC, jrbarnes9 commented
[uploading...]


<details><summary>Browser metadata</summary>





```
Path:      /components/checkboxes/
Browser:   Chrome 92.0.4515.159 on Mac OS 10.14.6
Viewport:  1331 x 794 @1x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1638--ons-design-system.netlify.app%2Fcomponents%2Fcheckboxes%2F&os=OS%20X&os_version=Mojave&browser=Chrome&browser_version=92.0&resolution=1331x794&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1638--ons-design-system.netlify.app/components/checkboxes/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6138b7e25c0bce00070c04e4&commentID=6138bbdbf0b403c596160abf&resolution=resolved)

2021-09-08 13:34 UTC, jrbarnes9 commented
![image](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNzc0N2FkYzgtYzY1MC00ODNkLWI1YTEtZDgzMDAzZjQ2MjAxIiwiZGVwbG95X2lkIjoiNjEzOGI3ZTI1YzBiY2UwMDA3MGMwNGU0IiwiaWQiOiJhOWVjMWFkYi05MTRlLTRmNDktYjc0YS02NDQ3YjcwNjNiODkifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /components/checkboxes/
Browser:   Chrome 92.0.4515.159 on Mac OS 10.14.6
Viewport:  1331 x 794 @1x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1638--ons-design-system.netlify.app%2Fcomponents%2Fcheckboxes%2F&os=OS%20X&os_version=Mojave&browser=Chrome&browser_version=92.0&resolution=1331x794&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1638--ons-design-system.netlify.app/components/checkboxes/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6138b7e25c0bce00070c04e4&commentID=6138bbf3048bf9c7e6dbc931&resolution=resolved)

2021-09-08 14:08 UTC, jrbarnes9 commented
![Uploading Screenshot 2021-09-08 at 15.08.16.png…]()

2021-09-08 14:17 UTC, jrbarnes9 requested changes

2021-09-08 14:17 UTC, jrbarnes9 commented on src/tests/spec/cookies/cookies-banner.spec.js
> +    '<div class="ons-cookies-confirmation-messageons-u-d-no">' +
```suggestion
    '<div class="ons-cookies-confirmation-message ons-u-d-no">' +
```

2021-09-08 14:17 UTC, jrbarnes9 commented on src/components/panel/_macro.njk
> +                        <{{ titleTag }} id="error-summary-title" {% if params is defined and params and params.type is defined and params.type %}data-qa="{{ params.type }}-header"{% endif %} class="o
```suggestion
                        <{{ titleTag }} id="error-summary-title" {% if params is defined and params and params.type is defined and params.type %}data-qa="{{ params.type }}-header"{% endif %} class="ons-panel__title ons-u-fs-r--b">{{ params.title | safe }}</{{ titleTag }}>
```

2021-09-08 14:17 UTC, jrbarnes9 commented on src/scss/utilities/_pad.scss
> +// e.gons-u-pl-m
```suggestion
// e.g ons-u-pl-m
```

2021-09-08 14:17 UTC, jrbarnes9 commented on src/pages/patterns/news/examples/article/index.njk
> +            <div class="ons-u-mt-lons-u-mt-xl@m">
```suggestion
            <div class="ons-u-mt-l ons-u-mt-xl@m">
```

2021-09-08 14:21 UTC, rmccar requested changes

2021-09-08 14:21 UTC, rmccar commented on src/components/button/index.njk
> +Use `ons-btn--disabled` with the `disabled=true` element attribute for buttons that have no event/action but need to be displayed.
```suggestion
Use `.ons-btn--disabled` with the `disabled=true` element attribute for buttons that have no event/action but need to be displayed.
```

2021-09-08 14:21 UTC, rmccar commented on src/components/summary/index.njk
> +                        "value": "<code>ons-summary__button</code>"
```suggestion
                        "value": "<code>.ons-summary__button</code>"
```

2021-09-08 14:23 UTC, rmccar commented
![image](https://user-images.githubusercontent.com/42928680/132527477-cb942ba0-8885-4564-a018-1977a7be0ce1.png)
Underline missing from skip to link

2021-09-08 15:04 UTC, boxadesign commented
> ![image](https://user-images.githubusercontent.com/42928680/132527477-cb942ba0-8885-4564-a018-1977a7be0ce1.png)
> Underline missing from skip to link

Won't do on this branch

2021-09-08 15:26 UTC, jrbarnes9 approved these changes

2021-09-08 15:46 UTC, merged