Added 'writing page titles' content guide
ONSdigital/design-system pull request #1640
Opened 2021-08-13 16:22 UTC by jrbarnes9

### What is the context of this PR?
- Added new page to 'get started' section about How to write page titles
- Grouped all the guides that aren't related to 'installing' into a new subgroup
- Renamed the design assets and browser compatibility page titles

### How to review
Check docs

2021-08-13 16:25 UTC, jrbarnes9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add documentation about descriptive page titles](https://trello.com/c/hNaLutxn/578-add-documentation-about-descriptive-page-titles)

2021-08-17 08:32 UTC, LauraC119 requested changes
1. Change this sentence: "Page titles are the first thing read out by screen readers and the link that is shown first on search results." to "Page titles are the first thing read out by screen readers and the link that shows in search results."
2. Change: 'if “Start survey” is used' to ' if you use “Start survey”' 
3. Change the two hyphens at the end to en dashes
4. Change "Include a suffix to each page title of the site name" to "Include the site name on the end of each page title"
5. Change "add the prefix “Error:” to each page title" to "add “Error:” at the start of each page title"
6. The link to error status doesn't work

2021-08-17 09:16 UTC, LauraC119 approved these changes

2021-08-17 12:36 UTC, boxadesign approved these changes

2021-08-18 07:53 UTC, merged