Fixed typos, broken/invalid links and hrefs and added missing namespacing
ONSdigital/design-system pull request #1683
Opened 2021-09-15 13:50 UTC by jrbarnes9

### What is the context of this PR?
Fixed any typos, broken/invalid links, hrefs and added missing namespacing

### How to review
Check links and examples work and are correct

2021-09-15 13:53 UTC, boxadesign submitted a review, later dismissed

2021-09-15 14:17 UTC, jrbarnes9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Broken links, examples and missing namespacing](https://trello.com/c/QWU6DPFA/1335-fix-broken-links-examples-and-missing-namespacing)

2021-09-15 14:37 UTC, LauraC119 requested changes
All the changes you made fine. Just spotted a couple of other things while checking them:
1.  components/summary/
"The summary can contain multiple question and answer types, and will adapt it's layout depending on the length of the strings."
Change "it's" to "its"

2. patterns/cookies-settings/
"following with cookieType name e.g. cookies-campaigns"
Change "e.g." to ", for example, "

2021-09-15 15:45 UTC, LauraC119 requested changes
1. In putting in the "for example"s there are quite a few places with double commas: 
label and select macro-options, button, page-template and typography 

2. And spotted another typo: 
address-input/macro-options **and** addresses/macro-options
change "resedential" to "residential"

2021-09-16 07:25 UTC, LauraC119 submitted a review, later dismissed

2021-09-16 13:04 UTC, LauraC119 approved these changes

2021-09-16 17:53 UTC, boxadesign approved these changes

2021-09-16 19:29 UTC, merged