Remove manual classes for variations
ONSdigital/design-system pull request #1684
Opened 2021-09-17 11:42 UTC by boxadesign

## BREAKING CHANGE
### What is the context of this PR?
The following components required the manual adding of classes to the `classes` param to use available variants. This is error prone and would produce unnecessary breaking changes in future:

- buttons
- lists
- input widths

Have introduced a new param to each component to set the variants. 

For buttons and lists the new param is `variants`. This accepts an array or single string value e.g. `'variants': ['small', 'secondary']` or `'variants': 'secondary'`.

For input widths the new paramer is `width`. e.g. `'width': '7@m'`. Previously the user had to use one or two classes (if number type or not) and this logic has now been automated in the macro (based on whether the type is number or tel). 

### What is the breaking change?

Developers will need to remove the manual classes being added to their component config and add the new appropriate param and value.

### How to review
Check everything is ok.

2021-09-17 14:59 UTC, jrbarnes9 commented
Needs a Percy check

2021-09-20 11:05 UTC, jrbarnes9 commented on src/patterns/correct-errors/examples/errors-proto/errors/index.njk
> +                "width": "2",
```suggestion
                "width": "3",
```

2021-09-20 11:54 UTC, rmccar commented
Looks good once Jons stuff is sorted

2021-09-20 14:05 UTC, jrbarnes9 commented
Needs to be updated to use width param? ![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNzc0N2FkYzgtYzY1MC00ODNkLWI1YTEtZDgzMDAzZjQ2MjAxIiwiZGVwbG95X2lkIjoiNjE0ODgwODk2NTMzZTMwMDA3MzAyYWQ5IiwiaWQiOiJjZjJiYjU1OS0yYzA4LTRhM2EtYjE1Mi0wNmMzZDA3ZTVlMzgifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /patterns/question/
Browser:   Chrome 93.0.4577.63 on Mac OS 10.14.6
Viewport:  1542 x 978 @1x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1684--ons-design-system.netlify.app%2Fpatterns%2Fquestion%2F&os=OS%20X&os_version=Mojave&browser=Chrome&browser_version=93.0&resolution=1542x978&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1684--ons-design-system.netlify.app/patterns/question/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=614880896533e30007302ad9&commentID=61489521af858f14405dff81&resolution=resolved)

2021-09-20 14:06 UTC, jrbarnes9 commented
Worth updating this dates documentation to mention width param instead of class? ![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNzc0N2FkYzgtYzY1MC00ODNkLWI1YTEtZDgzMDAzZjQ2MjAxIiwiZGVwbG95X2lkIjoiNjE0ODgwODk2NTMzZTMwMDA3MzAyYWQ5IiwiaWQiOiI0NWFmZTVlZi0wMDk4LTRmN2EtYTM0OS1mZGNkYjE1OGIxZTkifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /patterns/dates/
Browser:   Chrome 93.0.4577.63 on Mac OS 10.14.6
Viewport:  1542 x 978 @1x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1684--ons-design-system.netlify.app%2Fpatterns%2Fdates%2F&os=OS%20X&os_version=Mojave&browser=Chrome&browser_version=93.0&resolution=1542x978&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1684--ons-design-system.netlify.app/patterns/dates/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=614880896533e30007302ad9&commentID=6148957aaf858f1a8b5dfd14&resolution=resolved)

2021-09-21 14:53 UTC, LauraC119 requested changes
Those changes to the Width constrained section have made it even longer. 
Can you you cut the following: 
"Inputs can have their widths constrained (but not limited) to the number of expected characters using the width parameter."
and
"If you set type: text and width: 10 this will constrain the input to the width of 10 letters."

2021-09-22 07:44 UTC, LauraC119 submitted a review, later dismissed

2021-09-22 07:50 UTC, LauraC119 approved these changes
OK, I see you made Jon's change. All good from me

2021-09-22 08:21 UTC, jrbarnes9 approved these changes

2021-09-23 08:52 UTC, merged