Content guide for basic principles
ONSdigital/design-system pull request #1692
Opened 2021-09-22 10:33 UTC by jrbarnes9

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review
Describe the steps required to test the changes (include screenshots if appropriate).

2021-09-22 11:07 UTC, jrbarnes9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [5 basic content principles](https://trello.com/c/bwmJTQr7/1338-5-basic-content-principles)

2021-09-22 14:11 UTC, rmccar approved these changes

2021-09-23 11:23 UTC, LauraC119 requested changes
1. Remove 
- write for the reading comprehension of a 9-year-old or below (Grade 4 to 5 in the Hemingway app)

2. were we removing the "writing" from the page titles and URLs page? If so, need to remove it from the link under Bullet points

3. Remove "considerations" from the link at the end of the  Accessibility section

4. Remove "any" from the last sentence

2021-09-23 11:36 UTC, LauraC119 approved these changes

2021-09-23 11:39 UTC, rmccar approved these changes

2021-09-23 13:00 UTC, merged