Content guidance for question pattern
ONSdigital/design-system pull request #1693
Opened 2021-09-23 09:48 UTC by jrbarnes9

### What is the context of this PR?
Added guidance on how to write the elements of the question pattern.

### How to review
Check the docs in question pattern

2021-09-23 09:55 UTC, jrbarnes9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add content guidance for question pattern](https://trello.com/c/PNaR21tu/1344-add-content-guidance-for-question-pattern)

2021-09-23 11:12 UTC, LauraC119 requested changes
1. Change the bullet points on the first example so they start with lower-case letter

2. Under Question guidance, change:
Question guidance panels are for extra information that a "Use it to" to "Use them to" as talking about panels plural 

3. Under Question justification, change:
"phrase them as statements rather than questions"
to
"write them as statements rather than questions"

4. Change "Question with a interviewer instruction" to "Question with an interviewer instruction"

2021-09-23 11:29 UTC, LauraC119 approved these changes

2021-09-24 07:40 UTC, rmccar approved these changes

2021-09-24 08:29 UTC, merged