Added punctuation content guidance
ONSdigital/design-system pull request #1694
Opened 2021-09-23 10:41 UTC by jrbarnes9

### What is the context of this PR?
Added punctuation content guidance

### How to review
Check page in 'Guidance' section

2021-09-23 11:40 UTC, jrbarnes9 commented
![](https://github.trello.services/images/mini-trello-icon.png) ["Using punctuation" content guide](https://trello.com/c/TmEKw9cj/1339-using-punctuation-content-guide)

2021-09-23 11:40 UTC, LauraC119 requested changes
1. Change "panels (includes warning, padlock and thank you panels)" to "question guidance panels (includes warning, padlock and thank you panels)" as that's what we call the panels on the question pattern

2. Change "headers" to "headings" as that's what we call the panels on the question pattern

3. Remove full stop on the Exception panel

2021-09-23 13:19 UTC, LauraC119 approved these changes

2021-09-23 15:18 UTC, LauraC119 approved these changes

2021-09-24 08:33 UTC, rmccar approved these changes

2021-09-24 08:35 UTC, merged