Allow header titles to wrap above medium breakpoint
ONSdigital/design-system pull request #1751
Opened 2021-11-08 14:22 UTC by jrbarnes9

### What is the context of this PR?
- When long header titles wrap above `m` breakpoint, the container height remains fixed. This PR allows the height to increase when the title wraps.

### How to review
Check header variants with titles appropriately allow for long wrapping titles at all breakpoints.

2021-11-08 14:24 UTC, jrbarnes9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #1636: Header vertical spacing issue when header title wraps](https://trello.com/c/HD2KDBCr/1283-issue-1636-header-vertical-spacing-issue-when-header-title-wraps)

2021-11-09 14:12 UTC, rmccar commented on src/components/header/_macro.njk
> +                            <{{ title_tag }} class="ons-header__title{% if params.desc is defined and params.desc %} ons-header__title--with-description{% endif %}{% if params.button is defined and p
```suggestion
                            <{{ title_tag }} class="ons-header__title{% if params.desc is defined and params.desc %} ons-header__title--with-description{% endif %}{% if params.button is defined and params.button %} ons-header__title--with-button{% endif %}">{{ params.title }}</{{ title_tag }}>
```

2021-11-09 14:18 UTC, rmccar requested changes
Other than this looks good

2021-11-09 16:04 UTC, rmccar approved these changes

2021-11-10 12:39 UTC, boxadesign approved these changes

2021-11-10 15:06 UTC, merged