Added more config to onsQuestion
ONSdigital/design-system pull request #1804
Opened 2021-12-17 12:40 UTC by jrbarnes9

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review
Describe the steps required to test the changes (include screenshots if appropriate).

2022-01-11 12:19 UTC, boxadesign submitted a review, later dismissed
Appears to work

2022-01-11 14:55 UTC, jrbarnes9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #824: Ensure consistent vertical spacing in questionnaire templates](https://trello.com/c/dBfruIos/558-issue-824-ensure-consistent-vertical-spacing-in-questionnaire-templates)

2022-01-12 14:57 UTC, rmccar requested changes
Few small things

2022-01-12 14:57 UTC, rmccar commented on src/components/question/examples/question-fieldset/index.njk
> +  }
```suggestion
  "title": "Question example",
  "breadcrumbs": {
      "ariaLabel": 'Breadcrumbs',
      "itemsList": [
          {
              "url": '#0',
              "text": 'Previous'
          }
      ]
  }
```
Bit of a nit but indentation is inconsistent

2022-01-12 14:57 UTC, rmccar commented on src/components/question/_macro.njk
> +            {% if params.guidance.content %}
```suggestion
            {% if params.guidance.content is defined and params.guidance.content %}
```

2022-01-12 14:57 UTC, rmccar commented on src/components/question/_macro.njk
> +            {% endfor -%}
```suggestion
            {% if params.guidance.lists is defined and  params.guidance.lists %}
                {%- for item in params.guidance.lists -%}
                    {% if item.listHeading is defined and item.listHeading %}
                        <h2 class="ons-u-fs-r--b">{{ item.listHeading }}</h2>
                    {% endif %}
                    {% if item.listLeadingLine is defined and item.listLeadingLine %}
                        <p>{{ item.listLeadingLine }}</h2>
                    {% endif %}
                    {% from "components/lists/_macro.njk" import onsList %}
                    {{
                        onsList({
                            "itemsList": item.itemsList
                        })
                    }}
                {% endfor -%}
            {% endif -%}
```

Should probably check here if guidance.lists exists as its not mandatory and add is defined in a couple of places

2022-01-12 15:17 UTC, rmccar approved these changes

2022-01-14 09:56 UTC, boxadesign approved these changes

2022-01-18 09:35 UTC, merged