Section Navigation - create vertical variant
ONSdigital/design-system pull request #1805
Opened 2021-12-20 13:40 UTC by boxadesign

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review
Describe the steps required to test the changes (include screenshots if appropriate).

2022-01-18 12:29 UTC, jrbarnes9 approved these changes

2022-01-18 12:34 UTC, rmccar requested changes

2022-01-18 12:34 UTC, rmccar commented on src/components/section-navigation/_macro.njk
> +              {% if item.anchors is defined and item.anchors %}
Item.anchors needs to be added to the macro options

2022-01-24 12:43 UTC, jrbarnes9 approved these changes

2022-01-25 08:11 UTC, rmccar approved these changes

2022-01-25 09:33 UTC, merged