1797 search result
ONSdigital/design-system pull request #2011
Opened 2022-02-25 16:21 UTC by jrbarnes9

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review
Describe the steps required to test the changes (include screenshots if appropriate).

2022-03-08 15:42 UTC, kruncher approved these changes
Looks good to me. The only thing that I wonder about is the name of the component; i.e. `Document` vs something like `DocumentEntry` or `DocumentItem` since the component presents information about a document rather than being the actual document.

2022-03-10 09:43 UTC, kruncher approved these changes

2022-03-10 16:26 UTC, rmccar requested changes
Just these few things, other than that looks good

2022-03-10 16:26 UTC, rmccar commented on src/components/document-list/_macro.njk
> +                                {%- if document.metadata.file is defined and document.metadata.file %}
Need an if around this section including the fileType stuff that checks if `document.metadata` exists

2022-03-10 16:26 UTC, rmccar commented on src/components/document-list/_macro.njk
> +                                    {%- if document.metadata.type.text is defined and document.metadata.type.text %}
```suggestion
                                    {%- if document.metadata.type is defined and document.metadata.type and document.metadata.type.text is defined and document.metadata.type.text %}
```

2022-03-10 16:26 UTC, rmccar commented on src/components/document-list/_macro.njk
> +                                    {%- if document.metadata.file.fileType is defined and document.metadata.file.fileType %}
```suggestion
                                    {%- if document.metadata.file is defined and document.metadata.file and document.metadata.file.fileType is defined and document.metadata.file.fileType %}
```

2022-03-10 20:20 UTC, kruncher submitted a review, later dismissed

2022-03-11 10:53 UTC, rmccar approved these changes

2022-03-11 11:18 UTC, boxadesign commented
![image](https://user-images.githubusercontent.com/1015442/157857250-5d3a7f5a-b019-43f3-840c-5aa7a5a5939e.png)

Pagination layout issue on News pattern

2022-03-11 11:36 UTC, jrbarnes9 commented
> ![image](https://user-images.githubusercontent.com/1015442/157857250-5d3a7f5a-b019-43f3-840c-5aa7a5a5939e.png)
> 
> Pagination layout issue on News pattern


Yeah I raised a bug for this #2024

2022-03-11 11:38 UTC, boxadesign approved these changes

2022-03-21 10:42 UTC, merged