Wrapped timeout modal example in div with fixed height
ONSdigital/design-system pull request #2640
Opened 2023-03-24 16:04 UTC by jrbarnes9

### What is the context of this PR?
Fixes #2636

2023-03-24 16:32 UTC, jrbarnes9 commented
Needs to be tested in service manual embed locally, and then the version of the design system will need to be updated in the service manual before the fix is realised.

2023-06-07 09:51 UTC, alec-hamilton-ons requested changes

2023-06-07 11:57 UTC, alessioventuriniAND commented on src/components/timeout-modal/example-timeout-modal.njk
> +<div style="height:500px;">
all done :)

2023-06-07 11:57 UTC, alec-hamilton-ons approved these changes

2023-06-07 15:34 UTC, willcAND approved these changes

2023-06-07 15:39 UTC, alessioventuriniAND commented on src/components/timeout-modal/example-timeout-modal.njk
> +<div style="min-height:20rem;">
unfortunately not. U have checked what utility classes we have and none have been created for this specific use.

2023-06-07 15:39 UTC, merged