Bugfix - 2136 - Cookies Banner Param Rename
ONSdigital/design-system pull request #2688
Opened 2023-06-23 08:20 UTC by willcAND

[Issue 2136](https://github.com/ONSdigital/design-system/issues/2136)

### How to review
Checkout to branch locally, update example to include renamed parameter `contextSuffix`. Confirm still working as expected.

2023-06-23 10:28 UTC, precious-onyenaucheya-ons approved these changes
Please add a note to the description about the breaking change

2023-06-23 12:07 UTC, alessioventuriniAND requested changes
Please add another note to your PR to describe the steps to take to fix this breaking change locally

2023-06-26 08:24 UTC, alessioventuriniAND approved these changes

2023-06-26 08:35 UTC, precious-onyenaucheya-ons approved these changes

2023-06-26 09:20 UTC, merged