Feature/add params to overwrite default language in autosuggest component
ONSdigital/design-system pull request #2765
Opened 2023-07-27 13:25 UTC by precious-onyenaucheya-ons

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.
fixes #1919 
add language parameter to overwrite default language in autosuggest component

### How to review
Describe the steps required to test the changes (include screenshots if appropriate).

2023-07-28 09:00 UTC, alec-hamilton-ons requested changes

2023-07-28 11:20 UTC, rmccar commented on package.json
> +  "dependencies": {
The fix has already been merged into the `main` branch. So you just need to remove it from `dependencies`.

2023-07-28 14:19 UTC, alec-hamilton-ons approved these changes

2023-07-28 14:36 UTC, rmccar requested changes
We need to add some automated tests for this

2023-08-01 08:37 UTC, rmccar commented on src/components/autosuggest/autosuggest.spec.js
> +      expect(languageCount).toBeDefined;
Think we should check that this then equals what it is set to rather than just that its been defined

2023-08-10 11:39 UTC, rmccar approved these changes
Changes look ok. Tested as best I could in eQ but will have to do some more testing once merged just to be sure.

2023-08-11 11:08 UTC, merged