Update tags to headings in section navigation component
ONSdigital/design-system pull request #2964
Opened 2023-12-01 08:12 UTC by precious-onyenaucheya-ons

### What is the context of this PR?

The section navigation components consist of nested lists, with each section item having linked nested lists (which remain hidden until selected). This ticket proposes a modification to the current approach, suggesting that when a section item is selected, it should be changed from a link to a heading.

### How to review this PR

Go to the section navigation component and check that the selected section item is wrapped in a `header` tag and the other unselected ones are wrapped in` <a> `tag

### Checklist

This needs to be completed by the person raising the PR.

- [ ] I have selected the correct Assignee
- [ ] I have linked the correct Issue

2023-12-01 14:31 UTC, rmccar requested changes

2023-12-01 14:31 UTC, rmccar commented on src/components/section-navigation/_macro.njk
> +                            {% if item.anchors and isCurrent == true %}
There is duplication of logic here, could we not move this to the top and use a param like the `headingLevel` one

2023-12-01 14:31 UTC, rmccar commented on src/components/section-navigation/_macro.njk
> +    <h{{headingLevel}} class="ons-u-vh" id="{{ params.hiddenTitleId | default("section-menu-nav-title") }}">{{ params.hiddenTitle | default("Pages in this section") }}</h{{headingLevel}}>
```suggestion
    <h{{ headingLevel }} class="ons-u-vh" id="{{ params.hiddenTitleId | default("section-menu-nav-title") }}">{{ params.hiddenTitle | default("Pages in this section") }}</h{{ headingLevel }}>
```
The code format should be like this

2023-12-01 14:31 UTC, rmccar commented on src/components/section-navigation/example-section-navigation.njk
> -                "url": "#0"
I don't think this needs to change

2023-12-05 13:42 UTC, rmccar approved these changes

2023-12-05 14:24 UTC, alessioventuriniAND approved these changes

2023-12-05 14:54 UTC, merged