Added the active condition
ONSdigital/design-system pull request #2970
Opened 2023-12-05 13:58 UTC by SriHV

### What is the context of this PR?

Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review this PR

Describe the steps required to test the changes (include screenshots if appropriate).

### Checklist

This needs to be completed by the person raising the PR.

- [ ] I have selected the correct Assignee
- [ ] I have linked the correct Issue

2023-12-07 15:47 UTC, rmccar requested changes
The current change doesn't work and doesn't set the active class under the correct conditions. This suggestion below should fix it

2023-12-07 15:47 UTC, rmccar commented on src/components/navigation/_macro.njk
> +                        <li class="ons-navigation__item{{ ' ons-navigation__item--active' if (params.navigation.subNavigation.overviewURL == params.navigation.subNavigation.currentPath)}}">
```suggestion
                        <li class="ons-navigation__item{{ ' ons-navigation__item--active' if (params.navigation.subNavigation.overviewURL == params.navigation.subNavigation.currentPath) or (params.navigation.subNavigation.overviewURL == params.navigation.currentPath) or (params.navigation.currentPath is not string and params.navigation.subNavigation.overviewURL in params.navigation.currentPath) }}">
```
This change isn't working for me. But I updated it to this and after testing it, it works.

2023-12-11 09:13 UTC, rmccar commented
Other than the tests failing this now looks good

2023-12-11 13:37 UTC, rmccar approved these changes

2023-12-11 13:41 UTC, alessioventuriniAND approved these changes

2023-12-11 13:51 UTC, adi-unni approved these changes

2023-12-11 14:30 UTC, merged