add search functionality to ds
ONSdigital/design-system pull request #2977
Opened 2023-12-12 17:30 UTC by precious-onyenaucheya-ons

### What is the context of this PR?
Fixes #2872 
This ticket implements search functionality in the DS local frontend.
### How to review this PR

Check that there is a search input at the root of the DS local frontend. And that it implements autosuggests as well.
### Checklist

This needs to be completed by the person raising the PR.

- [ ] I have selected the correct Assignee
- [ ] I have linked the correct Issue

2023-12-13 08:56 UTC, rmccar requested changes
Unable to spin up the DS on this branch. It falls over because theres a missing `_dsTemplate.njk` file. Im not sure if this is meant to be a problem with the path or a file that hasn't been pushed

2023-12-13 08:56 UTC, rmccar commented on lib/dev-server.js
> +    const pageSearch = renderSearch(`${PROJECT_PATH}/templates/layout/_dsTemplate.njk`, nunjucksEnvironment);
This path either seems to be wrong or `_dsTemplate.njk` is missing

2023-12-13 08:56 UTC, rmccar commented on lib/dev-server.js
> +    await buildSearchIndex();
Config for the search should probably be added in config.indexPage.js because that is where the rest of the page is configured

2023-12-13 08:56 UTC, rmccar commented on lib/render-page-list.js
> +export default function renderPageList(pages, title, output = '') {
'output' isn't a good variable name here, its very undescriptive

2023-12-13 08:56 UTC, rmccar commented on src/static/examples/data/search-index.json
> +[{"en":"access-code","url":"/components/access-code","category":""},{"en":"accordion","url":"/components/accordion","category":""},{"en":"address-input","url":"/components/address-input","category":"
Shouldn't this file be git ignored because it should be created automatically?

2023-12-13 12:26 UTC, rmccar reviewed
Be nice to have a label on the search box. I know its only the dev front end but at the moment its just an input with no explanation what it is for. Also the results are pushing the links down the page

![Screenshot 2023-12-13 at 10 44 32](https://github.com/ONSdigital/design-system/assets/42928680/db817dad-f8cf-4989-aa62-5b5802d66481)

2023-12-13 13:59 UTC, rmccar commented on src/layout/_dsTemplate.njk
> +    "id": "search input-autosuggest",
Shouldn't have spaces in ids and I think something like this would be better

```suggestion
    "id": "component-pattern-autosuggest",
```

2023-12-13 14:00 UTC, rmccar commented
> Be nice to have a label on the search box. I know its only the dev front end but at the moment its just an input with no explanation what it is for. Also the results are pushing the links down the page
> 

Even just adding a placeholder to the input instead of a label would be good

2023-12-14 09:06 UTC, rmccar commented on src/layout/_dsTemplate.njk
> +{% from "components/input/_macro.njk" import onsInput %}
```suggestion
```

2023-12-14 09:15 UTC, rmccar commented on src/layout/_dsTemplate.njk
> +            "text": "Search this service",
```suggestion
            "text": "Search patterns and components",
```
Think this is better wording for this

2023-12-14 10:02 UTC, rmccar commented on src/layout/_dsTemplate.njk
> +        "classes": "ons-input-search ons-input-search--icon ons-input-search--dark",
```suggestion
        "classes": "ons-input-search ons-input-search--icon ons-input-search--dark ons-u-mb-s",
```
Adding this class improves the spacing

2023-12-14 13:34 UTC, rmccar approved these changes

2023-12-15 09:49 UTC, alessioventuriniAND approved these changes

2023-12-18 13:05 UTC, merged