updates access code text in line with style guide
ONSdigital/design-system pull request #2981
Opened 2023-12-14 16:00 UTC by balibirchlee

### What is the context of this PR?

Updates to Access Code text in line with style guide, around links, contractions and specificity. https://github.com/ONSdigital/design-system/issues/2959

### How to review this PR

Run locally and open out pages for access code & access code error - check text.

### Checklist

This needs to be completed by the person raising the PR.

- [?] I have selected the correct Assignee
- [x] I have linked the correct Issue

2023-12-15 11:13 UTC, rmccar requested changes
Moved the link text inside the link. Also the button can be removed from the details components, this seems to be left behind from the previous implementation. The button param has now been removed.

2023-12-15 11:13 UTC, rmccar commented on src/components/access-code/example-access-code-error.njk
> +        If you have lost or not received an access code, you can request a new access code <a href="#0">[LINK]</a>.
```suggestion
        If you have lost or not received an access code, you can <a href="#0">request a new access code</a>.
```

2023-12-15 11:13 UTC, rmccar commented on src/components/access-code/example-access-code-error.njk
> +        <p>If you need to answer separately from the people you live with, you can request an individual access code <a href="#0">[LINK]</a>.</p>
```suggestion
        <p>If you need to answer separately from the people you live with, you can <a href="#0">request an individual access code</a>.</p>
```

2023-12-15 11:13 UTC, rmccar commented on src/components/access-code/example-access-code.njk
> +        If you have lost or not received an access code, you can request a new access code <a href="#0">[LINK]</a>.
```suggestion
        If you have lost or not received an access code, you can <a href="#0">request a new access code</a>.
```

2023-12-15 11:13 UTC, rmccar commented on src/components/access-code/example-access-code.njk
> +        <p>If you need to answer separately from the people you live with, you can request an individual access code <a href="#0">[LINK]</a>.</p>
```suggestion
        <p>If you need to answer separately from the people you live with, you can <a href="#0">request an individual access code</a>.</p>
```

2023-12-15 14:35 UTC, rmccar commented on src/components/access-code/example-access-code-error.njk
> +
We don't want to remove the details component completely, just the button. Same with the other example

```suggestion
{% call onsDetails({
            "id": "details-access-code-error",
            "title": "Need to answer separately from your household?"
        })
    %}
        {{ content | safe }}
    {% endcall %}
```

2023-12-20 12:23 UTC, rmccar approved these changes

2024-01-02 10:31 UTC, alessioventuriniAND approved these changes

2024-01-15 15:08 UTC, alessioventuriniAND commented
replaced by #2993

2024-01-15 15:08 UTC, closed without merging