Update markdown
ONSdigital/design-system pull request #3097
Opened 2024-03-18 10:20 UTC by adi-unni

### What is the context of this PR?

Fixes: #3023 

Small error in documentation for language selector where in code `languages.abbrText` was described as `language.TextAbbr`. Fixed this

### How to review this PR

Check documentation for language selector

### Checklist

This needs to be completed by the person raising the PR.

- [x] I have selected the correct Assignee
- [x] I have linked the correct Issue

2024-03-18 10:52 UTC, precious-onyenaucheya-ons approved these changes

2024-03-18 10:59 UTC, alessioventuriniAND approved these changes

2024-03-21 08:24 UTC, rmccar requested changes
Change is good just also needs updating in the header macro options

2024-04-02 07:32 UTC, rmccar approved these changes

2024-04-08 10:00 UTC, merged