show tooltip when hovering over input with prefix/suffix
ONSdigital/design-system pull request #3130
Opened 2024-04-09 14:29 UTC by precious-onyenaucheya-ons

### What is the context of this PR?
fixes #2946 

This pull request introduces the functionality to display tooltips when hovering over inputs with both prefix and suffix. Additionally, corresponding tests have been added to ensure proper functionality.

### How to review this PR

Verify that inputs with either a prefix or suffix display the tooltip when hovered over.

### Checklist

This needs to be completed by the person raising the PR.

- [ ] I have selected the correct Assignee
- [ ] I have linked the correct Issue

2024-04-09 15:58 UTC, alessioventuriniAND approved these changes

2024-04-10 14:42 UTC, adi-unni commented
Scope of original ticket has changed. According to #2411 the ticket wanted the title text to be displayed when the input was in focus, not just when the input area is hovered over. As I understand, this change is not possible without reworking the component and is not backed up with user research for need so happy to approve in this current state

2024-04-10 14:43 UTC, adi-unni approved these changes

2024-04-11 07:51 UTC, rmccar requested changes
Im not sure this is needed? Has this ticket been raised because something has been missed on the original issue? The original issue was asking for the tooltip to be added when hovering over the `<abbr>` this is used to give meaning to the abbreviation in the prefix/suffix and they usually have titles for this purpose. I don't think it was asking for the tooltip to also be added to the input.

2024-04-12 10:26 UTC, closed without merging