Update babel preset-env
ONSdigital/design-system pull request #3175
Opened 2024-05-03 09:56 UTC by rmccar

### What is the context of this PR?

Fixes: #3174

This updates `@babel/preset-env` to remove the caniuse-lite warning. It also updates the lock file so there will be other dependencies within that that are updated unless they are pinned to a specific version but this will be limited minor updates

### How to review this PR

- Run `yarn start` on main, see that the warning is printed in the terminal
- Run `yarn start` on this branch, see that the warning is now gone

### Checklist

This needs to be completed by the person raising the PR.

- [ ] I have selected the correct Assignee
- [ ] I have linked the correct Issue

2024-05-07 08:31 UTC, alessioventuriniAND approved these changes

2024-05-08 11:21 UTC, balibirchlee requested changes

2024-05-09 08:15 UTC, rmccar commented on src/components/header/_macro-options.md
Yep thats fair, Ill move it out into another PR 👍

2024-05-09 14:28 UTC, rmccar commented on src/components/header/_macro-options.md
Removed and added in #3188

2024-05-16 13:19 UTC, balibirchlee approved these changes

2024-05-17 14:49 UTC, SriHV approved these changes

2024-05-17 22:19 UTC, merged