Refactor share-page macro to suit Jinja2 templates
ONSdigital/design-system pull request #3177
Opened 2024-05-07 10:59 UTC by SriHV

### What is the context of this PR?

#3170... Removed `.push` method which was used for adding facebook and twitter icons to a list. This is done to make share-page work in Jinja templates as well.

### How to review this PR

-Test the changes in Design system
- Pull the late PR ([link](https://github.com/ONSdigital/design-system-python-flask-demo/pull/3)) thats in review. Follow the updated readme
- Update the macro and test it in Jinja template

### Checklist

This needs to be completed by the person raising the PR.

- [ ] I have selected the correct Assignee
- [ ] I have linked the correct Issue

2024-05-08 10:04 UTC, alessioventuriniAND approved these changes

2024-05-08 10:47 UTC, precious-onyenaucheya-ons approved these changes

2024-05-09 08:10 UTC, rmccar approved these changes

2024-05-09 08:12 UTC, rmccar requested changes
Line 9 in the macro can now be removed

2024-05-09 13:38 UTC, rmccar approved these changes

2024-05-13 11:14 UTC, merged