Refactor timeline macro to suit Jinja2 templates
ONSdigital/design-system pull request #3180
Opened 2024-05-08 09:50 UTC by SriHV

### What is the context of this PR?
#3171 ... In timeline component `items` is replaced with items_timeline as `.items()` is a built in function for looping dictionaries in python 

### How to review this PR

- Test the changes in Design system
- Pull the latest PR ([link](https://github.com/ONSdigital/design-system-python-flask-demo/pull/3)) which is in review. Follow the updated readme.
- Update the macro and test it in Flask.

### Checklist

This needs to be completed by the person raising the PR.

- [ ] I have selected the correct Assignee
- [ ] I have linked the correct Issue

2024-05-08 10:08 UTC, alessioventuriniAND reviewed
I am not sure I understand what has been changed? Looks like a parameter name has been changed from items to items_timeline but I didn't see any .items() functions?

2024-05-09 08:16 UTC, rmccar commented
> > I am not sure I understand what has been changed? Looks like a parameter name has been changed from items to items_timeline but I didn't see any .items() functions?
> 
> oh sorry I wasn't clear. Items is a reserved name mainly used as a built-in function for dictionary data structure. So when trying to iterate over this parameter named 'items', we get this error `'builtin_function_or_method' object is not iterable`.

Can this information be put into the description

2024-05-09 09:51 UTC, rmccar commented
Can we have a "breaking changes" section added to the description that tells the user how to update their service to fix the breaking change we have introduced

2024-05-09 14:13 UTC, rmccar commented on src/components/timeline/example-timeline.njk
> +    "timelineItems": [
Looks good, just the indentation needs to be fixed here in this example

2024-05-09 15:00 UTC, rmccar commented on src/components/timeline/example-timeline.njk
> -    "timelineItems": [
Only this line needed indenting, the rest of the example is fine

2024-05-10 12:05 UTC, rmccar commented on src/components/timeline/example-timeline.njk
> +            ]
```suggestion
            {
                "heading": 'September to October 2020',
                "itemsList": [
                    {
                        "text": "Meet your Community Engagement Manager and set up regular catch up meetings"
                    },
                    {
                        "text": "Local Authority Toolkit available online"
                    }
                ]
            },
            {
                "heading": 'September 2020',
                "content": '<p>ONS to provide Councillor Handbook for distribution</p>'
            },
            {
                "heading": 'November 2020',
                "content": '<p>ONS to provide you with content for magazines and publications</p>'
            },
            {
                "heading": 'January to March 2021',
                "content": '<p>ONS to provide a range of press releases for external use</p>'
            },
            {
                "heading": 'February to April 2021',
                "content": '<p>Promote your local Census Support Centres</p>'
            }
        ]
```

This is what I was suggesting

2024-05-17 09:12 UTC, alessioventuriniAND requested changes
As richard said can you please add a Breaking change section to explain how users can fix this in their service?

2024-06-17 10:23 UTC, alessioventuriniAND approved these changes

2024-06-17 11:08 UTC, precious-onyenaucheya-ons approved these changes

2024-09-06 15:37 UTC, merged