Changed PoweredBy param to include a link
ONSdigital/design-system pull request #3201
Opened 2024-05-13 08:19 UTC by SriHV

### What is the context of this PR?

#3164...  Previously, there is no option to include a link around poweredBy logo when  custom logo is used. Changed poweredBy param to include.

### How to review this PR
Check that poweredBy param has two parameters `logoImage` and `logoUrl`. 
Test example-footer-with-alternative-organisation to ensure these parameters are shown

### Checklist

This needs to be completed by the person raising the PR.

- [ ] I have selected the correct Assignee
- [ ] I have linked the correct Issue

2024-05-14 14:46 UTC, balibirchlee commented
Not sure how this fits together with the changes Precious made to the  poweredby functionality recently - I think we'll need to discuss in the next tech session.

2024-05-16 07:11 UTC, rmccar requested changes
I think some of these issues (at least the focus state one) might have been solved in the other footer PR. You can have a look at that https://github.com/ONSdigital/design-system/pull/3153

2024-06-04 08:23 UTC, alessioventuriniAND reviewed
It all looks good. Can you please fix the focus state that Richard has mentioned? 

For reference , more work will be completed on the footer logo on this issue. #3134 

This changes can still be applied as the afore mentioned issue is currently being re-worked/expanded on as the original requirements have changed therefore it is not longer a blocker for this issue. :)

2024-06-04 13:40 UTC, alessioventuriniAND commented on src/components/footer/_footer.scss
> +  }
Looks like this change is removing the underline to the default logo. 
![Screenshot 2024-06-04 at 14 39 31](https://github.com/ONSdigital/design-system/assets/112873190/3d9d6258-d67a-460b-a373-c619e229e584)

2024-06-10 10:42 UTC, SriHV commented
This change is already being addressed in this #3134 PR. Closing this ticket

2024-06-10 10:42 UTC, closed without merging