Add Pre-set value in a textarea within a radio
ONSdigital/design-system pull request #3257
Opened 2024-07-08 13:38 UTC by SriHV

### What is the context of this PR?

#3242... Added a preset value for a radio option that has textarea

### How to review this PR
Add a preset value to one of the radio examples with a textarea option, and verify that the value is displayed.

### Checklist

This needs to be completed by the person raising the PR.

-   [x] I have selected the correct Assignee
-   [x] I have linked the correct Issue

2024-07-09 09:21 UTC, alessioventuriniAND approved these changes

2024-07-09 11:59 UTC, precious-onyenaucheya-ons approved these changes

2024-07-09 15:26 UTC, rmccar requested changes
Some minor changes

2024-07-09 15:26 UTC, rmccar commented on src/components/radios/_macro.spec.js
> +const EXAMPLE_RADIO_ITEM_WITH_PRESET_TEXTAREA = {
```suggestion
const EXAMPLE_RADIO_ITEM_TEXTAREA_WITH_PRESET_VALUE = {
```
More consistent with other example names

2024-07-09 15:26 UTC, rmccar commented on src/components/radios/_macro.spec.js
> +        id: 'other-textbox-radio-with-text-input',
```suggestion
        id: 'other-textarea-input',
```
Should be named something like this to be consistent with other examples and it specifies its a textarea not a text input

2024-07-09 15:26 UTC, rmccar commented on src/components/radios/_macro.spec.js
> +        value: 'other-answer',
```suggestion
        value: 'other answer',
```
This should be an answer someone would write in the text area so for it to be a good example it shouldn't be hyphenated

2024-07-11 13:35 UTC, rmccar approved these changes

2024-07-11 13:44 UTC, merged