update ons-grid--flex to ons-grid-flex
ONSdigital/design-system pull request #3268
Opened 2024-07-15 10:55 UTC by precious-onyenaucheya-ons

### What is the context of this PR?

Fixes #3259. This PR renames utility class from `ons-grid--flex` to `ons-grid-flex`.

Please note that this may be a breaking change.

**How to Resolve the Breaking Change**

1. Search your codebase for any occurrences of `ons-grid--flex`.
2. Replace all instances with the new class name `ons-grid-flex`.

### How to review this PR

1. Verify that all instances of ons-grid--flex have been renamed to ons-grid-flex.
2. Ensure that all references in the documentation, examples, and tests have been updated accordingly.
3. Confirm that all tests pass.

### Checklist

This needs to be completed by the person raising the PR.

-   [ ] I have selected the correct Assignee
-   [ ] I have linked the correct Issue

2024-07-16 09:06 UTC, alessioventuriniAND requested changes
Looking at the ticket it doesn't seem like the request has been fully met. 

By changing the class to ons-grid-flex you then also want the other utility classes that only work with with display flex to be modifiers of the class ons-grid-flex. 

So they would look like this : 

```
ons-grid-flex--between
ons-grid-flex--vertical-center
etc..
```

2024-07-18 08:53 UTC, alessioventuriniAND approved these changes

2024-07-18 12:38 UTC, rmccar commented
The PR description needs updating. Also as you have now started using the sass syntax in this file I was wondering if we want to restructure the rest of this file using sass syntax

2024-07-22 11:18 UTC, SriHV approved these changes

2024-07-25 07:23 UTC, rmccar approved these changes

2024-09-05 10:58 UTC, merged