Fix/3263/focus states broken on internal header
ONSdigital/design-system pull request #3269
Opened 2024-07-16 09:19 UTC by alessioventuriniAND

### What is the context of this PR?

This fixes : #3263 

The focus of the logo is now aligned with the rest of our headers variants and the service link focus state too. 

### How to review this PR

Move to the internal header example and tab through the elements and confirm that the focus state has the expected styling. 

### Checklist

This needs to be completed by the person raising the PR.

-   [ ] I have selected the correct Assignee
-   [ ] I have linked the correct Issue

2024-07-16 13:36 UTC, balibirchlee reviewed
looks good to me and all works as expected

2024-07-16 13:39 UTC, balibirchlee approved these changes

2024-07-16 15:02 UTC, SriHV approved these changes

2024-07-17 09:11 UTC, precious-onyenaucheya-ons approved these changes

2024-07-17 10:00 UTC, rmccar requested changes
<img width="414" alt="Screenshot 2024-07-17 at 10 57 13" src="https://github.com/user-attachments/assets/faac5266-92f4-4794-8846-9c7f4034fdf9">

The focused hover isn't right here. I think it should either be black and not white or not have any change like the title link. Might need to check with Dina, if its the latter this will also need to be fixed in the neutral header too

2024-07-17 10:28 UTC, rmccar approved these changes

2024-07-17 12:36 UTC, merged