Replace thumbnail image
ONSdigital/design-system pull request #3277
Opened 2024-07-29 11:50 UTC by precious-onyenaucheya-ons

### What is the context of this PR?

This PR fixes https://github.com/ONSdigital/ons-service-manual-website/issues/400
The thumbnail  image for document list and card component was replaced to have a darker fill color('--ons-color-image-placeholder').

### How to review this PR

Check that all thumbnail images in the project has been updated
Check that all visual tests is updated accordingly
 
### Checklist

This needs to be completed by the person raising the PR.

-   [ ] I have selected the correct Assignee
-   [ ] I have linked the correct Issue

2024-08-02 13:52 UTC, alessioventuriniAND requested changes

2024-08-02 13:52 UTC, alessioventuriniAND commented on backstop_data/bitmaps_reference/ds-vr-test__patterns_download-resources_example-download-resources_0_document_0_desktop.png
The border of the portrait placeholder image needs to have the same color as the new one and the focus state background color needs be changed to the new one.

2024-08-02 15:41 UTC, precious-onyenaucheya-ons commented on backstop_data/bitmaps_reference/ds-vr-test__patterns_download-resources_example-download-resources_0_document_0_desktop.png
updated

2024-08-05 12:55 UTC, alessioventuriniAND approved these changes

2024-08-08 09:54 UTC, rmccar requested changes
Few minor things

2024-08-08 09:56 UTC, rmccar commented
<img width="195" alt="Screenshot 2024-08-08 at 10 54 55" src="https://github.com/user-attachments/assets/07726563-33cb-4551-b00d-44825cd1fef1">

Focus state looks slightly off, adding "!important" after "outline-offset: 0" on line 135 in the document list css file will solve this

2024-08-08 12:52 UTC, precious-onyenaucheya-ons commented on src/components/document-list/document-list.scss
done

2024-08-08 12:52 UTC, precious-onyenaucheya-ons commented on src/components/document-list/document-list.scss
> -            background-color: var(--ons-color-image-placeholder) !important;
removed

2024-08-09 09:28 UTC, merged