Enhancement/69/change utility classes to 8px grid
ONSdigital/design-system pull request #3285
Opened 2024-08-06 11:07 UTC by alessioventuriniAND

### What is the context of this PR?

Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review this PR

Describe the steps required to test the changes (include screenshots if appropriate).

### Checklist

This needs to be completed by the person raising the PR.

-   [ ] I have selected the correct Assignee
-   [ ] I have linked the correct Issue

2024-09-25 10:42 UTC, SriHV commented on src/components/list/_list.scss
> +            // margin-bottom: -0.5;
Can we remove &:last-child? Cause margin-bottom is commented here

2024-09-26 14:22 UTC, rmccar requested changes
Some initial comments

2024-09-26 14:48 UTC, rmccar commented
<img width="185" alt="Screenshot 2024-09-26 at 15 47 30" src="https://github.com/user-attachments/assets/6831ca2e-446b-4c7f-823d-c20b4f1408d5">
<img width="217" alt="Screenshot 2024-09-26 at 15 47 38" src="https://github.com/user-attachments/assets/f12f1d48-37db-4ad7-990d-f4c377260c15">
The loader button and link buttons don't look like they're aligned correctly

2024-09-26 15:06 UTC, rmccar commented
Adding this here 
<img width="240" alt="Screenshot 2024-09-26 at 16 05 49" src="https://github.com/user-attachments/assets/33312e1f-87ad-457f-ae23-d0c54d8551f6">

Has caused the terms here to not be in bold, is that supposed to be like that? Because it looks odd now to me
<img width="367" alt="Screenshot 2024-09-26 at 16 04 23" src="https://github.com/user-attachments/assets/b77a771a-2f62-4fae-beba-032da43466fb">

2024-09-26 15:14 UTC, rmccar commented
We now have a gap between the warning panel and the footer because of this being changed to use a utility class which now has "!important" on it
<img width="241" alt="Screenshot 2024-09-26 at 16 13 24" src="https://github.com/user-attachments/assets/b4ca038f-45bb-4975-ad6d-958a5ff152ee">

<img width="797" alt="Screenshot 2024-09-26 at 16 09 47" src="https://github.com/user-attachments/assets/2704b00c-08cb-48cb-ab53-b3533d020368">

2024-09-26 15:23 UTC, rmccar commented
The list summary variant doesn't seem quite aligned especially the second and third items here

<img width="210" alt="Screenshot 2024-09-26 at 16 22 24" src="https://github.com/user-attachments/assets/4287b5d2-72ce-432b-9547-4c3c3b17684f">

2024-09-26 15:29 UTC, rmccar commented
The exclamation mark icon isn't aligned

<img width="218" alt="Screenshot 2024-09-26 at 16 28 25" src="https://github.com/user-attachments/assets/842274f8-65fb-49ee-a853-5537ab6c8302">

2024-09-26 15:40 UTC, rmccar commented
Similar to the social list the share page component isn't aligned
<img width="183" alt="Screenshot 2024-09-26 at 16 39 06" src="https://github.com/user-attachments/assets/e3d91815-fc50-435f-abf6-88b0b6755bf1">

2024-09-26 15:46 UTC, rmccar commented
The timeline titles aren't aligned

<img width="284" alt="Screenshot 2024-09-26 at 16 45 07" src="https://github.com/user-attachments/assets/d1afac2d-8b7e-493d-8e04-fd97c5cbc087">

2024-09-27 09:06 UTC, rmccar commented on src/scss/vars/_forms.scss
> +$nbsp-width: 0.288rem; // adjusted from 0.256rem
Probably need to remove these comments now

2024-09-30 12:56 UTC, SriHV commented on src/components/download-resources/_download-resources.scss
>      &__results-options {
Should this changed to utilty class as well?

2024-10-02 13:20 UTC, SriHV commented
<img width="837" alt="Screenshot 2024-10-02 at 14 18 31" src="https://github.com/user-attachments/assets/84c2a078-5a6e-4069-9b19-6c23a33b08ea">
View Cookies link is in the next line now in cookie banner example. Is this alright?

2024-10-03 09:25 UTC, rmccar commented on src/components/card/_macro.spec.js
> +            expect($('#example-title-id').text().trim()).toBe('Example card title');
The changes adding this id can be reverted now and instead of setting the id in a few places in this test file we can go back to using the class

2024-10-03 12:44 UTC, rmccar commented
The icon is misshapen on the error in the address example 

<img width="970" alt="Screenshot 2024-10-03 at 13 43 18" src="https://github.com/user-attachments/assets/19a9aeb3-e494-4648-baac-bb7c408ba3ea">

2024-10-03 16:27 UTC, SriHV approved these changes

2024-10-04 07:16 UTC, rmccar commented on src/components/quote/_quote.scss
> +        margin-top: 2r0.5m;
Got a typo here

2024-10-04 07:19 UTC, rmccar commented on src/components/hero/_hero.scss
> +                //text-decoration: underline solid var(--ons-color-text-inverse-link) 1px;
This can be removed if its not needed

2024-10-04 07:30 UTC, rmccar commented on src/scss/vars/_grid.scss
> +    xxl: 1600px,
What made you revert these changes?

2024-10-04 07:42 UTC, rmccar commented on src/scss/objects/_page.scss
> +    margin-top: 2.5rem;
This could be `margin: 2.5rem 0 4rem;`

2024-10-04 07:43 UTC, rmccar commented on src/components/list/_list.scss
> +            margin-bottom: 0.5rem;
This could be `margin: 0 0 0.5rem;`

2024-10-04 07:46 UTC, rmccar commented on src/components/field/_field.scss
> +            margin-right: 0.5rem;
margin: 0 0.5rem 0 0;

2024-10-04 07:48 UTC, rmccar commented on src/components/download-resources/_download-resources.scss
> +            margin-right: 0.5rem;
This could be `margin: 0 0.5rem 0 0;`

2024-10-04 07:59 UTC, rmccar commented on src/components/navigation/_navigation.scss
> +        @extend .ons-u-mb-no;
Here we are adding a margin bottom and then removing it. We might be able to remove both these lines

2024-10-04 10:38 UTC, rmccar reviewed
The warning panel icon css needs updating, the icon is now smaller. Check the Figma but if its meant to be the same size you will need to up the `line-height` `min-height` and `min-width` to 2.25rem

2024-10-04 10:40 UTC, rmccar reviewed
The warning panel icon overrides in the the autosuggest css probably need converting to rems

2024-10-04 12:08 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
> +-   **Description of change:** Icon sizes have been updated with the new naming size standard.
Think this needs a bit more information like what has been done for the padding above

2024-10-04 12:08 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
> +-   **Description of change:** font sizes have been updated with the new naming size standard.
Same here a bit more information

2024-10-04 12:08 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
> +             'ons-u-fs-s'
Needs a bit of aligning here

2024-10-04 20:08 UTC, rmccar commented on src/components/autosuggest/_autosuggest.scss
> +            top: 1.0625rem;
font-size: 1.3rem;
line-height: 1.5rem;
margin-top: 0;
min-height: 1.5rem;
min-width: 1.5rem;
top: 1rem

Think these should be this. I dont think theres a need for them to be that specific and the `min-height` and `min-width` need to be the same value to make the icon circular

2024-10-04 20:16 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
> +### **_Update to icon sizes naming standard_**
I think the wording of this is a bit more clear

### **_Standardisation of breakpoint size naming_**

[**Link to PR**](https://github.com/ONSdigital/design-system/pull/3285)

-   **Description of change:** The breakpoint naming convention has been updated to match other size naming like the padding and margin sizes. The old breakpoint size names like xxs and xxl have been replaced with 2xs, 2xl, and so on, to better align with other size naming.

-   **Reason for change:** The new naming convention standardises how breakpoints are referenced across the design system.

-   **Components impacted:**

    Any component or layout that references breakpoints using the previous naming convention will need to be updated.

-   **Migration steps:**

    1. Locate all instances of breakpoints in your codebase.
    2. Replace old breakpoint names with the new corresponding names:

2024-10-04 20:18 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
> +    2. Replace old breakpoint names with the new corresponding names:
I think the wording of this is a bit more clear

### **_Standardisation of breakpoint size naming_**

[**Link to PR**](https://github.com/ONSdigital/design-system/pull/3285)

-   **Description of change:** The breakpoint naming convention has been updated to match other size naming like the padding and margin sizes. The old breakpoint size names like xxs and xxl have been replaced with 2xs, 2xl, and so on, to better align with other size naming.

-   **Reason for change:** The new naming convention standardises how breakpoints are referenced across the design system.

-   **Components impacted:**

    Any component or layout that references breakpoints using the previous naming convention will need to be updated.

-   **Migration steps:**

    1. Locate all instances of breakpoints in your codebase.
    2. Replace old breakpoint names with the new corresponding names:

2024-10-04 20:22 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
> +### **_Update to icon sizes naming standard_**
I think this is worded a bit better

### **_Standardisation of font size naming_**


[**Link to PR**](https://github.com/ONSdigital/design-system/pull/3285)

-   **Description of change:** Font size classes have been updated to reflect the new size naming convention in the Design System. This update replaces the old naming convention (e.g., xxxl, xxl) with a numerical system (e.g., 3xl, 2xl), similar to the one used for padding and margins.

-   **Reason for change:** This update standardises how sizes are referenced across the system

-   **Components impacted:**

    Any component or layout where you use the xxl or xxxl font-size utility classes.

-   **Migration steps:**

    1. Locate all instances of the font size utility classes in your codebase.
    2. Replace old size name with new corresponding size name:

2024-10-04 20:28 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
>  -   **Components impacted:**
I think this is worded a bit better and is more consistent with others

### **_Standardisation of font size naming_**

[**Link to PR**](https://github.com/ONSdigital/design-system/pull/3285)

-   **Description of change:** Font size classes have been updated to reflect the new size naming convention in the Design System. This update replaces the old naming convention (e.g., xxxl, xxl) with a numerical system (e.g., 3xl, 2xl), similar to the one used for padding and margins.

-   **Reason for change:** This update standardises how sizes are referenced across the system

-   **Components impacted:**

    Anywhere you use the xxl or xxxl font-size utility classes.

-   **Migration steps:**

    1. Locate all instances of the font size utility classes in your codebase.
    2. Replace old size name with new corresponding size name:

2024-10-07 10:27 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
> +-   **Description of change:** Icon sizes have been updated with to new size naming standard. This change replaces the old naming convention (e.g., xxxl, xxl) with a numerical system (e.g., 3xl, 2xl)
```suggestion
-   **Description of change:** Icon sizes have been updated to reflect the new size naming convention. This change replaces the old naming convention (e.g., xxxl, xxl) with a numerical system (e.g., 3xl, 2xl), the same as the one that has been brought for padding and margins.
```

2024-10-07 10:30 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
> +-   **Description of change:** Font size classes have been updated to reflect the new size naming convention in the Design System. This update replaces the old naming convention (e.g., xxxl, xxl) wit
```suggestion
-   **Description of change:** Font size classes have been updated to reflect the new size naming convention. This change replaces the old naming convention (e.g., xxxl, xxl) with a numerical system (e.g., 3xl, 2xl), the same as the one that has been brought for padding and margins.
```

2024-10-07 10:33 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
> +-   **Reason for change:** This update standardises how sizes are referenced across the system
```suggestion
-   **Reason for change:** This update standardises how sizes are referenced across the system.
```

2024-10-07 10:38 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
> +-   **Description of change:** The breakpoint naming convention has been updated to match other size naming like the padding and margin sizes. The old breakpoint size names like xxs and xxl have been
```suggestion
-   **Description of change:** Breakpoint size names have been updated to reflect the new size naming convention. This change replaces the old naming convention (e.g., xxxl, xxl) with a numerical system (e.g., 3xl, 2xl), the same as the one that has been brought for padding and margins.
```

2024-10-08 13:08 UTC, rmccar approved these changes

2024-10-08 14:47 UTC, merged