Update Fuse config to increase search threshold
ONSdigital/design-system pull request #3288
Opened 2024-08-08 12:58 UTC by precious-onyenaucheya-ons

### What is the context of this PR?

This PR fixes #3282 

This PR updates the Fuse.js configuration to address an issue where only the first 30 characters in the list seem to be searched.

The previous threshold setting of 0.2 was too strict, causing the search to miss relevant entries when the query length increased. By increasing the threshold to 0.6, we allow for more flexibility in the search, ensuring that longer entries are still matched appropriately even as the query becomes more specific.

### How to review this PR

Describe the steps required to test the changes (include screenshots if appropriate).

1. Run the search functionality with the updated configuration.
2. Perform a search for "South Georgia and the South Sandwich Islands".
3. Verify that the search result appears when searching for "South Sa" and similar queries.

### Checklist

This needs to be completed by the person raising the PR.

-   [ ] I have selected the correct Assignee
-   [ ] I have linked the correct Issue

2024-10-17 08:23 UTC, rmccar commented
The description now needs updating with the latest changes

2024-10-17 08:44 UTC, rmccar requested changes

2024-10-17 14:14 UTC, rmccar commented
I think there may be an issue with this not working as expected, I upped the threshold to 0.8 in the example and was still getting the same results. So you may need to make sure that is being passed into the config correctly

2024-10-18 12:45 UTC, rmccar submitted a review, later dismissed

2024-10-18 13:01 UTC, rmccar commented
Im not sure this is defaulting to 0.2, when removing the setting of the param from the example the results are a lot stricter. Also the attribute is still being set just without a value which I dont think we should be doing

2024-10-21 07:14 UTC, rmccar submitted a review, later dismissed

2024-10-27 22:17 UTC, admilne commented
@precious-onyenaucheya-ons @rmccar 

Sorry, I ran out of time to look at this on Friday after running into some git permission issues Precious is aware of but I wanted to take a look before you have stand up in the morning. I'm not sure if I've misunderstood the ticket and the requirements - it wasn't entirely clear for me but this doesn't look like it's working to me. Could be I'm not looking at it correctly but once I hit around 32 characters in the search box it no longer returns the results I'd expect. I've taken some screen shots to illustrate what I experienced.

- "South Georgia and the South San" - returns what i'd expect
- "South Georgia and the South Sand" - doesn't seem to return anything
- "South Georgia and the South Sandw" - gives me some results, but doesn't seem to be based on anything I've searched for
- "South Georgia and the South Sandwich Island" - still appears to give me results not based on my search
- "South Georgia and the South Sandwich Islands" - suddenly seems to kick back in to life and return an expected result.

I tried playing with the thresholds but this didn't seem to make any difference to the issues I've described above.

<img width="433" alt="Screenshot 2024-10-27 at 22 06 23" src="https://github.com/user-attachments/assets/b7c78c06-e1bb-4c3b-8824-ed998e1c17cb">
<img width="428" alt="Screenshot 2024-10-27 at 22 06 34" src="https://github.com/user-attachments/assets/9edc7a06-6021-40ee-95c8-e2a098ce0ece">
<img width="428" alt="Screenshot 2024-10-27 at 22 06 51" src="https://github.com/user-attachments/assets/51330246-5af1-4b38-91bb-5f07e9272935">
<img width="421" alt="Screenshot 2024-10-27 at 22 07 09" src="https://github.com/user-attachments/assets/81e562d0-0923-4f67-bdd2-3b69252d32ea">
<img width="409" alt="Screenshot 2024-10-27 at 22 07 20" src="https://github.com/user-attachments/assets/26367582-8930-4302-a241-84f292eb6c1a">

2024-10-28 11:12 UTC, adi-unni commented on src/components/autosuggest/_macro-options.md
> +| resultsThreshold    | integer                              | false    | Option to adjust the search threshold and fuzziness. Accepts a range from 0 to 1, where 0 provides the closest match and 1 al
Just being very nit-picky but it isn't technically an integer. Maybe "float" would be more appropriate?

2024-10-28 11:51 UTC, adi-unni commented
I'd also like to second @admilne's findings. I've also done some additional testing with some of my own examples. 
I created a new JSON file with only examples of search terms which are longer than 32 characters. It seems like the search threshold doesn't change the results when typing. Whats more worrysome is the fact that words outside of the 32 character soft limit aren't picked up by fuse.

<img width="417" alt="image" src="https://github.com/user-attachments/assets/230800c5-3dad-46f2-8d43-842f711af574">

In this picture, you can see `this` is a search term. You can also see the word `characters` in the search terms which is the 54th character in the field

<img width="389" alt="image" src="https://github.com/user-attachments/assets/6a602110-e1d6-48a0-a0c8-98f921f77ffa">

Characters does not return anything in this scenario

This might seem like an edge case but say there was a scenario where a user wanted to match this: 

_Ultra HD 4K Smart Television Model XYZ1234567890_

based on the model number which is outside of 32 characters

You can test my changes in: [feature/3282/increase-search-threshold-adi](https://github.com/ONSdigital/design-system/tree/feature/3282/increase-search-threshold-adi)

2024-10-28 13:38 UTC, rmccar commented on src/components/autosuggest/autosuggest.ui.js
> +        const distance = threshold >= 0.6 ? 500 : threshold >= 0.4 ? 300 : 100;
I don't think chaining ternaries together is a good idea, its not very readable. You are probably better off just using if else

2024-10-29 07:44 UTC, rmccar commented
> * South Georgia and the South Sand

After the changes that have been made with the distance param these issues seem to have fixed by upping the threshold to 0.4 in my testing. But the issues Andrew highlighted still seem to be an issue

2024-10-29 07:52 UTC, rmccar commented
> I'd also like to second @admilne's findings. I've also done some additional testing with some of my own examples. I created a new JSON file with only examples of search terms which are longer than 32 characters. It seems like the search threshold doesn't change the results when typing. Whats more worrysome is the fact that words outside of the 32 character soft limit aren't picked up by fuse.
> 
> <img alt="image" width="417" src="https://private-user-images.githubusercontent.com/56112669/380698812-230800c5-3dad-46f2-8d43-842f711af574.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODY2ODUsIm5iZiI6MTczMDE4NjM4NSwicGF0aCI6Ii81NjExMjY2OS8zODA2OTg4MTItMjMwODAwYzUtM2RhZC00NmYyLThkNDMtODQyZjcxMWFmNTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA3MTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZTJjZjAxYmI2M2E1ODQ0NDM4YjkxOWI3ODdhOTcxZTExYTZiOTliNDkwZjg4MWUwMGFkZGQ3MTVlNzg1OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yIsTGrXkGaiItNTCX5ORI5RZLgdqJ-M9CtoC9YDBCS8">
> In this picture, you can see `this` is a search term. You can also see the word `characters` in the search terms which is the 54th character in the field
> 
> <img alt="image" width="389" src="https://private-user-images.githubusercontent.com/56112669/380699715-6a602110-e1d6-48a0-a0c8-98f921f77ffa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODY2ODUsIm5iZiI6MTczMDE4NjM4NSwicGF0aCI6Ii81NjExMjY2OS8zODA2OTk3MTUtNmE2MDIxMTAtZTFkNi00OGEwLWEwYzgtOThmOTIxZjc3ZmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA3MTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNzk1YjQ5Y2JiODMwYTgzNGU1OGQwZWE5YzAyZjEyYzhlMWY1YjZjMjE2ZDY5ODFjYTMxNjA1M2VmZjkwYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XxVP7-_hElkxyuT8_dsy66GPdEcupDNuHTcDcnODr6g">
> Characters does not return anything in this scenario
> 
> This might seem like an edge case but say there was a scenario where a user wanted to match this:
> 
> _Ultra HD 4K Smart Television Model XYZ1234567890_
> 
> based on the model number which is outside of 32 characters
> 
> You can test my changes in: [feature/3282/increase-search-threshold-adi](https://github.com/ONSdigital/design-system/tree/feature/3282/increase-search-threshold-adi)
> 
> **Edit: Actually in even more testing, back to the original example (testing in countries-multiple), if you type "sandwich islands", you'd expect "South Georgia and the South Sandwich Islands" to appear but nothing appears**
> 
> Edit 2: Even weirder, if you search for "thi" in the search box in my example, you get matches for "thi" beyond 32 characters? Not sure if this is because its previously matched "thi" at the beginning.
> 
> <img alt="image" width="406" src="https://private-user-images.githubusercontent.com/56112669/380708297-0008aead-df8e-4b15-8b18-953f35142a8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODY2ODUsIm5iZiI6MTczMDE4NjM4NSwicGF0aCI6Ii81NjExMjY2OS8zODA3MDgyOTctMDAwOGFlYWQtZGY4ZS00YjE1LThiMTgtOTUzZjM1MTQyYThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA3MTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZTA1OTA3OTAwODc3NDM4YTc5NmU1Yjc5ZDZmNTczNWQ0ODgyZjUyNmE4NzA4ODM1NzNiMTI0YjVjZjk0N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CK8tt62qK5XLU909yV9_O9ewl2f1JhsKTMx8AgvT5-Y">

These issues seem to have fixed by upping changing the distance to 500 in my testing without changing the threshold at all. So maybe we need to parameterise the distance not the threshold. But the issues Andrew highlighted still seem to be an issue. There might be an issue with the length of the query string entered which would cause the issues Andrew has found. This all needs bit more testing to make sure we get a balance between the distance and threshold. Testing with ignoreLocation might also be something we want to look into.

2024-10-29 13:42 UTC, adi-unni approved these changes

2024-10-31 09:48 UTC, rmccar commented
Ive found an issue with the component search on the DS. It finds the list of components when you start typing the name of a component but no longer goes to that page when you click the suggestion. There is this error in the console:
<img width="517" alt="Screenshot 2024-10-31 at 09 48 00" src="https://github.com/user-attachments/assets/91e602cc-88ca-438a-b552-e0acab488895">

2024-11-05 10:20 UTC, rmccar commented on src/components/autosuggest/autosuggest.ui.js
> +                    console.log(listElement);
Think this has been left in by accident

2024-11-06 12:25 UTC, SriHV approved these changes

2024-11-06 13:30 UTC, admilne approved these changes
LGTM and looks like it's working as expected

2024-11-07 15:31 UTC, merged