Change Parameter Naming convention in Message list
ONSdigital/design-system pull request #3291
Opened 2024-08-12 16:41 UTC by SriHV

### What is the context of this PR?
[#86](https://github.com/ONSdigital/design-team/issues/86)... 

As per the ticket tech notes, subject is made an object with text and url params.
Updated _macro-options.md file
 
### How to review this PR

Check the changes in example /patterns/send-and-reply-to-messages/example-message-list

### Checklist

This needs to be completed by the person raising the PR.

-   [ ] I have selected the correct Assignee
-   [ ] I have linked the correct Issue

2024-08-13 10:22 UTC, precious-onyenaucheya-ons reviewed
Please update the description to include a description for the breaking change

2024-08-14 14:13 UTC, precious-onyenaucheya-ons approved these changes

2024-08-15 12:22 UTC, rmccar requested changes

2024-08-15 12:22 UTC, rmccar commented on src/components/message-list/_macro-options.md
> +| subject  | `Object<Subject>` | true     | Settings for the [Subject]                                             |
If you are going to use the "[Subject]" syntax here to create a link you need a url in brackets after it

2024-08-16 07:40 UTC, rmccar approved these changes

2024-09-05 10:55 UTC, merged