Major release
ONSdigital/design-system pull request #3349
Opened 2024-09-13 12:53 UTC by alessioventuriniAND

### What is the context of this PR?

This Pr gets all our breaking changes ready for our major release on the 9th of October. 

The below PRs have been merged in the major-release branch : 

- #3111 
- #3188
- #3268 
- #3275 
- #3143 
- #3290 
- #3291 
- #3227 
- #3294 
- #3293 
- #3292
- #3295 
- #3224 
- #3180 
- #3299 
- #3300 
- #3303 
- #3304 
- #3305 
- #3306 
- #3307
- #3336 

### How to review this PR

Double check that all the PR that have been merged are correctly working as expected.

### Checklist

This needs to be completed by the person raising the PR.

-   [x] I have selected the correct Assignee
-   [x] I have linked the correct Issue

2024-09-24 10:59 UTC, rmccar requested changes
Just noticed a couple of typos

2024-09-24 10:59 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
> +                "unreadLinkUrl": "www.gooogle.com"
```suggestion
                "unreadLinkUrl": "www.google.com"
```

2024-09-24 10:59 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
> +                "src": "www.gooogle.com"
```suggestion
                "src": "www.google.com"
```

2024-09-24 10:59 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
> +                       },
```suggestion
                   "metadata": {
                       "type": {
                           "text": 'Press releases',
                           "ref": 'Ref 008052'
                       },
                   },
```

2024-09-24 10:59 UTC, rmccar commented on migration_guides/70.x.x-to-71.0.0-migration-guide.md
> +                       },
```suggestion
                   "metadata": {
                       "object": {
                           "text": 'Press releases',
                           "ref": 'Ref 008052'
                       },
                   },
```

2024-09-26 15:07 UTC, precious-onyenaucheya-ons commented on src/components/address-input/_macro-options.md
>  | manualLink              | string                                                        | false                            | url for the link displayed below the input
The manualLink has been updated to manualLinkUrl

2024-10-09 13:35 UTC, rmccar approved these changes

2024-10-09 13:54 UTC, precious-onyenaucheya-ons approved these changes

2024-10-09 13:59 UTC, merged