Refactor button test file to new format
ONSdigital/design-system pull request #3353
Opened 2024-09-13 16:06 UTC by SriHV

### What is the context of this PR?

[139](https://github.com/orgs/ONSdigital/projects/21/views/1?pane=issue&itemId=72216585)

Refactored the button macro.spec file as per the new format.

### How to review this PR

Ask yourself....
- Do we need any additional tests?
- Are the tests descriptions clear?
- Does the order of the test document make sense?
- Is it internally consistent?
- Is it consistent with the [guidelines for test refactoring](https://confluence.ons.gov.uk/display/SDC/Testing+Refactor+Guidance)? 

run this test command to view the test results:
`yarn test --testNamePattern="FOR: browser-banner"`

### Checklist

This needs to be completed by the person raising the PR.

-   [ ] I have selected the correct Assignee
-   [ ] I have linked the correct Issue

2024-09-18 14:33 UTC, rmccar commented on src/components/button/_macro.spec.js
> +describe('FOR: button', () => {
```suggestion
describe('FOR: Macro: Button', () => {
```

2024-09-18 14:34 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN; renders `button` element', () => {
```suggestion
            it('THEN; renders button element', () => {
```

2024-09-18 14:45 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders the provided `id` attribute', () => {
```suggestion
            it('THEN: renders the provided id attribute', () => {
```

2024-09-18 14:49 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders an `a` element', () => {
```suggestion
            it('THEN: renders an <a> element', () => {
```

2024-09-18 14:50 UTC, rmccar commented on src/components/button/_macro.spec.js
> +        describe('WHEN: link parameter is provided', () => {
```suggestion
    describe('GIVEN: Params: url', () => {
        describe('WHEN: url parameter is provided', () => {
```

2024-09-18 14:51 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: contains the provided link', () => {
```suggestion
            it('THEN: the link points to the provided url', () => {
```

2024-09-18 14:52 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: contains arrow-next icon by default', () => {
```suggestion
            it('THEN: the link button contains arrow-next icon by default', () => {
```

2024-09-18 14:53 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: does not have the download attribute', () => {
```suggestion
            it('THEN: the button does not have the download attribute', () => {
```

2024-09-18 14:54 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THENL renders additionally provided style classes', () => {
```suggestion
            it('THEN: the button has the additionally provided style classes', () => {
```

2024-09-18 14:55 UTC, rmccar commented on src/components/button/_macro.spec.js
> +    describe('GIVEN: params: removeDownloadattribute', () => {
```suggestion
    describe('GIVEN: Params: removeDownloadattribute', () => {
```

2024-09-18 14:55 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders additionally provided inner style classes', () => {
```suggestion
            it('THEN: the button inner has the additionally provided inner style classes', () => {
```

2024-09-18 14:56 UTC, rmccar commented on src/components/button/_macro.spec.js
> +        describe('WHEN: link parameter is provided, newWindow is true and newWindowDescription is provided', () => {
```suggestion
        describe('WHEN: url parameter is provided, newWindow is true and newWindowDescription is provided', () => {
```

2024-09-18 15:00 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders a default new window description', () => {
```suggestion
            it('THEN: has default new window description', () => {
```

2024-09-18 15:00 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: contains a custom new window description', () => {
```suggestion
            it('THEN: has custom new window description', () => {
```

2024-09-18 15:29 UTC, rmccar requested changes
These are mainly just minor things but it would be good to be consistent with the way we are writing these tests. We need to make sure we use the correct names for params and the tests describe what they are testing

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +        describe('WHEN: link parameter is provided and newWindow is true', () => {
```suggestion
        describe('WHEN: url parameter is provided and newWindow is true', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders expected style classes', () => {
```suggestion
            it('THEN: has expected style classes', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders the provided type attribute', () => {
```suggestion
            it('THEN: has the provided type attribute', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders the provided type attribute if variant contains print', () => {
```suggestion
            it('THEN: has the provided type attribute if variant contains print', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: defaults to being a submit button when type is not provided', () => {
```suggestion
            it('THEN: defaults to being a submit button', () => {
```
This is already in the when

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: defaults to being a button if variants contains print', () => {
the "if variants contains print" should be in a when

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders the provided type attribute if variant contains print', () => {
"if variant contains print" should be in a when

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders print icon when variants contains print', () => {
```suggestion
            it('THEN: button has the print icon', () => {
```

"when variants contains print" is already in the above when

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders provided variant style classes', () => {
```suggestion
            it('THEN: the button has the timer classes', () => {
```
Theres no classes provided, these are automatically set

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: loader icon when variants contains loader', () => {
```suggestion
            it('THEN: the button has the loader icon', () => {
```
Already in the above when

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders provided variant style classes', () => {
```suggestion
            it('THEN: the button has the loader classes', () => {
```
No classes have been provided these are automatic

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +        describe('WHEN: attributes is given as parameter', () => {
```suggestion
        describe('WHEN: the attributes param is provided', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +        describe('WHEN: there are no params given', () => {
```suggestion
        describe('WHEN: there are no params provided', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +    describe('GIVEN: Params: standard', () => {
```suggestion
    describe('GIVEN: Params: text, name and value', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +        describe('WHEN: button component is set with standard params', () => {
```suggestion
        describe('WHEN: text, name and value params are provided', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +        describe('WHEN: id is given as parameter', () => {
```suggestion
        describe('WHEN: the id param is provided', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders expected style classes', () => {
```suggestion
            it('THEN: has expected style classes', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +        describe('WHEN: text is given as parameter', () => {
```suggestion
        describe('WHEN: the text param is provided', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders label text', () => {
```suggestion
            it('THEN: the button has the label text', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders button context text', () => {
```suggestion
            it('THEN: the button has the provided button context', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders label text', () => {
```suggestion
            it('THEN: the button label has the provided html', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders custom icon before button text', () => {
```suggestion
            it('THEN: renders custom icon after button text', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders provided variant style classes', () => {
```suggestion
            it('THEN: the button has the expected variant classes', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders the download attribute when variants contains download', () => {
```suggestion
            it('THEN: the button has the download attribute', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders provided variant style class', () => {
```suggestion
            it('THEN: the button has the download class', () => {
```

2024-09-18 15:29 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: renders download icon', () => {
```suggestion
            it('THEN: the button has the download icon', () => {
```

2024-11-08 11:26 UTC, rmccar commented on src/components/button/_macro.spec.js
> +            it('THEN: has expected style classes', () => {
All the thens in this file should be using "test" and not "it"

2024-11-08 15:53 UTC, rmccar commented on src/components/button/_macro.spec.js
> +    describe('GIVEN: Params: additonal classes', () => {
```suggestion
    describe('GIVEN: Params: additional classes', () => {
```

2024-11-08 15:53 UTC, rmccar commented on src/components/button/_macro.spec.js
> +        describe('WHEN: innerclasses parameter is provided', () => {
```suggestion
        describe('WHEN: innerClasses parameter is provided', () => {
```

2024-11-08 15:54 UTC, rmccar commented on src/components/button/_macro.spec.js
> +        describe('WHEN: variants contains download and removeDownloadAttribute is true', () => {
```suggestion
        describe('WHEN: variants contains download and removeDownloadAttribute is true', () => {
```

2024-11-08 15:54 UTC, rmccar commented on src/components/button/_macro.spec.js
> +    describe('GIVEN: Params: removeDownloadattribute', () => {
```suggestion
    describe('GIVEN: Params: removeDownloadAttribute', () => {
```

2024-11-08 16:03 UTC, rmccar commented
We need tests for the following attributes to make sure they are being tested:
- name
- value
- iconType
- listeners

2024-11-13 08:55 UTC, rmccar approved these changes

2024-11-13 11:27 UTC, rmccar approved these changes

2024-11-13 12:15 UTC, admilne approved these changes

2024-11-13 16:48 UTC, merged