Add text-area variant to Checkbox component
ONSdigital/design-system pull request #3403
Opened 2024-10-22 13:36 UTC by precious-onyenaucheya-ons

### What is the context of this PR?

Fixes #3402 

This PR introduces a new variant of the Checkboxes component. The new variant includes an integrated text area that allows users to input text, with a character limit checker to ensure the input doesn't exceed the specified limit.

### How to review this PR

- Check that text area variant has been added with a character limit checker
- Check that all unit and visual tests pass
- 
### Checklist

This needs to be completed by the person raising the PR.

-   [ ] I have selected the correct Assignee
-   [ ] I have linked the correct Issue

2024-10-24 08:27 UTC, rmccar requested changes
Few minor things, other than this looks good

2024-10-24 08:27 UTC, rmccar commented on src/components/checkboxes/example-checkboxes-with-text-area-and-character-limit.njk
> +                        "id": "other-textbox-example-checkbox-with-revealed-text-area",
This id should either match the others and have `text-input` on the end or they should all be `text-area`

2024-10-24 08:27 UTC, rmccar commented on src/components/checkboxes/example-checkboxes-with-text-area-and-character-limit.njk
> +                            "limit": 400,
The radio textarea examples set this to 200, should probably make that consistent

2024-10-24 08:27 UTC, rmccar commented on src/components/checkboxes/_macro.spec.js
> +    describe('checkbox item with text area', () => {
We should text the maxlength attribute here to be set to what the char limit should be

2024-10-28 08:16 UTC, rmccar requested changes

2024-10-28 12:01 UTC, rmccar commented on src/components/checkboxes/example-checkboxes-with-revealed-text-area-and-character-limit-expanded.njk
> +                        }
This line still needs to be formatted

2024-10-28 12:01 UTC, rmccar commented
Just need to remove the old vr screenshots from the PR now

2024-10-29 06:58 UTC, rmccar requested changes

2024-10-29 13:25 UTC, adi-unni approved these changes

2024-10-29 14:23 UTC, rmccar approved these changes

2024-10-29 22:41 UTC, merged