Refactor Fieldset component
ONSdigital/design-system pull request #3435
Opened 2024-11-21 11:55 UTC by adi-unni

### What is the context of this PR?

Fixes: [#156](https://github.com/ONSdigital/design-team/issues/156)

Refactors the fieldset component test file to the new agreed format.

### How to review this PR
Run tests locally and check that the messages make sense and describe what is being tested

Ask yourself....

- Do we need any additional tests?
- Are the tests descriptions clear?
- Does the order of the test document make sense?
- Is it internally consistent?
- Is it consistent with the [guidelines for test refactoring](https://confluence.ons.gov.uk/display/DS/Testing+Refactor+Guidance)?
- run this test command to view the test results:
- `yarn test --testNamePattern="FOR: Macro: Fieldset"`

-   [x] I have selected the correct Assignee
-   [x] I have linked the correct Issue

2024-11-22 14:24 UTC, rmccar requested changes

2024-11-28 14:14 UTC, adi-unni commented on src/components/fieldset/_macro.spec.js
> +            test('THEN: legend has correct `aria-describedby` attribute', () => {
Just to be clear, its removing the apostrophes. Not the test right?

2024-11-28 14:27 UTC, rmccar commented on src/components/fieldset/_macro.spec.js
> +            test('THEN: legend has correct `aria-describedby` attribute', () => {
Yes

2024-12-06 09:31 UTC, rmccar commented on src/components/fieldset/_macro.spec.js
> +            test('THEN: legend has class "ons-fieldset__legend--with-description"', () => {
```suggestion
            test('THEN: legend has the legend with description class', () => {
```

2025-03-07 10:09 UTC, rmccar commented on src/components/fieldset/_macro.spec.js
> +    });
I would just move this THEN into the "WHEN: legend is provided" test and remove all this

2025-03-27 14:53 UTC, rmccar commented on src/components/fieldset/_macro.spec.js
> +    });
I think this still needs to be addressed, I dont think we need this test to have its own WHEN

2025-05-01 14:47 UTC, adi-unni commented on src/components/fieldset/_macro.spec.js
> +    });
Just pushed a change for this now

2025-05-08 15:37 UTC, SriHV approved these changes

2025-05-09 09:18 UTC, janehughes approved these changes
Tests look good and are all passing 👍

2025-05-09 09:41 UTC, merged