Add new "grey" hero variant
ONSdigital/design-system pull request #3450
Opened 2024-12-09 13:40 UTC by precious-onyenaucheya-ons

### What is the context of this PR?

[ONSDESYS-165](https://jira.ons.gov.uk/browse/ONSDESYS-165)....

Created new Hero variant as per the [Figma](https://www.figma.com/design/Yf4Cpxc8vYdoVrWcJojk2R/New-Website-Platform?node-id=255-18366&node-type=text&m=dev).It has a grey background with logo on the right.

This new variant will also have Breadcrumbs, title, sub-header and horizontal description list(link to the [PR](https://github.com/ONSdigital/design-system/pull/3439))

Prototype [link](https://nwp-prototype.ons.gov.uk/business-industry-and-trade/retail-industry/retail-sales/october-2024/)

Due to the changes in the HTML structure, I adjusted the styling by removing the margin applied to the text element when followed by a button. Instead, I added a margin to the top of the button to ensure consistent spacing.

### How to review this PR

Check that new src/components/hero/example-hero-grey.njk in Hero component matches the figma design

### Checklist

This needs to be completed by the person raising the PR.

-   [x] I have selected the correct Assignee
-   [x] I have linked the correct Issue

2024-12-18 15:47 UTC, admilne commented
@precious-onyenaucheya-ons it looks like there are a couple of differences to the design and what is asked for in the description of the ticket.

1. It looks like the first couple of items in the breadcrumb are missing in the mobile view. Also, the arrows change direction for mobile.
2. Again in mobile view, the logo should appear after the title but before the text. It's currently appearing after the text.
3. Might be worth checking the gap between the topic key word ('Analysis') and the title. It looks like there is a smaller gap in the design.

This is the screenshot running the component locally
![image](https://github.com/user-attachments/assets/205d8bc6-5dac-4fac-be0d-f929a1523d00)

This is the screenshot of the design in Figma
![image](https://github.com/user-attachments/assets/d420ac64-0211-4a72-8628-07c9b7f182de)

2024-12-18 17:29 UTC, admilne commented on src/components/hero/_hero.scss
> +        color: var(--ons-color-branded) !important;
I'm not sure we need the `!important` here

2024-12-18 17:29 UTC, admilne commented on backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-analysis_0_document_1_tablet.png
I think the design shows the logo coming after the title but before the text, rather than after the text.

2024-12-18 17:29 UTC, admilne commented on backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-analysis_0_document_2_mobile.png
A number of the breadcrumbs have disappeared and they don't in the design. Also, the arrows are now facing the opposite direction.

2024-12-18 17:29 UTC, admilne commented on src/components/hero/_macro.njk
> +                    <h2 class="ons-hero--topic">{{ params.topic | safe }}</h2>
This isn't wrapped in an if statement so if they don't supply a topic you end up with an empty h2 tag

2024-12-18 17:29 UTC, admilne commented on src/components/hero/_macro.spec.js
Should we also have a test for the logo?

2024-12-19 09:00 UTC, rmccar requested changes

2024-12-19 09:02 UTC, rmccar commented on backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-analysis_0_document_2_mobile.png
This one might just be an oversight in the design because thats how our breadcrumbs component is supposed to work. Can you double check with the designers to confirm this

2024-12-19 15:03 UTC, precious-onyenaucheya-ons commented on src/components/hero/_macro-options.md
> +| button          | `Object<Button>`                                          | false    | Settings for the hero [call to action button](#button)
I only documented the parameters that were added as part of this ticket.

2024-12-19 20:55 UTC, admilne commented on backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_1_tablet.png
Worth checking the margin below the topic. It looks like the gap is smaller in the design
<img width="1233" alt="image" src="https://github.com/user-attachments/assets/e0786e19-243c-4231-aca0-410dc0713048" />

2024-12-19 20:55 UTC, admilne commented on backstop_data/bitmaps_reference/ds-vr-test__components_hero_example-hero-grey_0_document_0_desktop.png
I think we may have a slight issue with the description list. One of the requirements is:

`description list component added horizontally and it can include text or hyperlinks - https://jira.ons.gov.uk/browse/ONSDESYS-189`

I don't think we can currently have links in here.

2024-12-20 12:45 UTC, admilne approved these changes

2025-01-06 09:08 UTC, rmccar commented
Now this is called the "grey" variant the title and description should be updated

2025-01-06 10:39 UTC, rmccar commented on src/components/hero/_hero.scss
> +        background-color: #efeff0;
We should probably have a var for this

2025-01-06 10:47 UTC, rmccar commented on src/components/hero/_macro-options.md
> +| badge           | boolean                                                   | false    | Set to “true” display the Oficial statistics badge in the hero
This param name should be renamed to something more descriptive because it can only add the official statistics badge. Maybe `officialStatisticsBadge`

2025-01-06 10:58 UTC, rmccar commented on src/components/hero/example-hero-analysis.njk
The padding top is still much bigger than in the figma

2025-01-06 12:20 UTC, rmccar commented on src/scss/vars/_colors.scss
> +    --ons-color-pale-grey: #efeff0;
Think this should be called `--ons-color-grey-10` and be put in between 15 and 5

2025-01-06 12:35 UTC, rmccar commented on src/components/hero/_macro-options.md
> +| badge           | boolean                                                   | false    | Set to “true” display the Oficial statistics badge in the hero
This will need to be updated in the macro too

2025-01-06 12:40 UTC, SriHV commented on src/components/hero/_macro-options.md
> +| badge           | boolean                                                   | false    | Set to “true” display the Oficial statistics badge in the hero
sorry forgot about that, changed it now

2025-01-06 12:42 UTC, rmccar commented on src/components/hero/example-hero-analysis.njk
This is the last thing I have that needs addressing, I think the padding top just needs reducing when using breadcrumbs

2025-01-10 09:53 UTC, rmccar commented on src/components/hero/_hero.scss
> +    }
This needs to be changed when the breadcrumbs is used not when we use the grey variant

2025-01-13 13:18 UTC, rmccar commented on src/components/hero/_macro.njk
> +                            "classes": 'ons-u-pt-no ' ~ (params.breadcrumbs.classes | default(''))
```suggestion
                            "classes": 'ons-u-pt-no ' ~ (params.breadcrumbs.classes if params.breadcrumbs.classes else '')
```

Good spot but I would change it to this, bit more explicit and what we have used elsewhere

2025-01-13 16:01 UTC, rmccar commented on src/components/hero/_macro.njk
> +                            "classes": 'ons-u-pt-no ' ~ (params.breadcrumbs.classes if params.breadcrumbs.classes else '')
```suggestion
                            "classes": 'ons-u-pt-no' ~ (' ' + params.breadcrumbs.classes if params.breadcrumbs.classes else '')
```
Sorry it should be this to avoid unnecessary spaces

2025-01-13 16:01 UTC, rmccar commented on src/components/hero/_macro.njk
> +                            "classes": 'ons-u-mt-s' + btnClasses,
We should probably do the same here. Can you test this

2025-01-13 17:07 UTC, SriHV commented on src/components/hero/_macro.njk
> +                            "classes": 'ons-u-mt-s' + btnClasses,
We are checking this already here like this
```
                    {% set btnClasses = params.button.classes if params.button.classes else '' %}
                    {% if params.variants and 'dark' in params.variants %}
                        {% set btnClasses = btnClasses + ' ons-btn--ghost' %}
                    {% endif %}
```
I think we don't need it here

2025-01-14 08:31 UTC, rmccar approved these changes

2025-01-14 10:48 UTC, merged