Moved description into dl tag in message list component
ONSdigital/design-system pull request #3465
Opened 2024-12-24 17:23 UTC by SriHV

### What is the context of this PR?

Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review this PR

Describe the steps required to test the changes (include screenshots if appropriate).

### Checklist

This needs to be completed by the person raising the PR.

-   [ ] I have selected the correct Assignee
-   [ ] I have linked the correct Issue

2025-01-06 10:15 UTC, rmccar requested changes

2025-01-07 15:25 UTC, admilne approved these changes

2025-01-09 12:45 UTC, rmccar commented on src/components/message-list/_macro.njk
> +                        aria-label="{{ params.ariaLabelMsg | default("Message text") }}"
We shouldn't need this line anymore

2025-01-09 12:46 UTC, rmccar commented on src/components/message-list/_macro.spec.js
> -    });
I think these actually need to just be repurposed to test that the new message params do what we expect because I don't think we need the aria attribute anymore

2025-01-10 11:03 UTC, rmccar commented
As this is a deprecation we need to follow the process outlined in the "Deprecation Implementation and Release Process" in confluence we have set out. You have added the "(DEPRECATED)" tag but we need to follow the other parts of the process

2025-01-10 14:07 UTC, rmccar requested changes

2025-01-10 14:07 UTC, rmccar commented on src/components/message-list/_macro.spec.js
> -    ariaLabelMsg: 'Message preview',
As we still support this param we still need to test it. We will need to add an example in where this is set instead of `bodyLabel` and a test similar to the new test you have added

2025-01-10 14:07 UTC, rmccar commented on src/components/message-list/_macro.spec.js
> +            bodyLabel: 'Body',
This param shouldn't be at the message level, it should be at the top param level like the other label params

2025-01-14 09:11 UTC, rmccar commented on src/components/message-list/_macro.njk
> +                        {{ params.bodyLabel | default("Message text") }}:
The way this is written allows both to be set and then both to be passed into the HTML, but we want one or the other. Currently when I test it with both params both pieces of text are rendered. We want `bodyLabel` to be the only one used if both are set. Then if one of the two are set that one is used. There is also currently a bit of an odd bug where if only `ariaLabelMsg` is set what it is set to is rendered but also "Message text:" is added on the end

<img width="594" alt="Screenshot 2025-01-14 at 09 09 20" src="https://github.com/user-attachments/assets/ff676728-3eb5-49b1-975a-8a0d13b67c0f" />

Tests need to be written for all these situations to make sure we have coverage and the test that is there will need to be checked because this should make the test fail

2025-01-14 09:13 UTC, rmccar commented on src/components/message-list/_macro.spec.js
>  };
This doesnt need to be its own example config as its only being used in one test at the moment you can just add the param in that test. Also the name needs updating because it should be all in caps

2025-01-15 09:18 UTC, rmccar approved these changes

2025-01-22 11:56 UTC, merged