Fix tabbing after clicking Skip to content link
ONSdigital/design-system pull request #957
Opened 2020-09-03 14:20 UTC by rmccar

### What is the context of this PR?
Fixes #852 

### How to review 
Add a skip to content link and a couple of input fields with a paragraph of main content between them to a page and check the tabbing order after clicking the skip to content link. When tabbing after clicking the link it should go focus on the input below the content, not the one above.

2020-09-04 13:27 UTC, boxadesign commented on src/components/skip-to-content/skip-to-content.js
> +    document.getElementById(id).focus();
What happens if there is no input on the page? `scrollIntoView` works on any element with the provided `id` but `focus` relies on a focusable element being the target.

2020-09-04 13:29 UTC, boxadesign commented on src/components/skip-to-content/skip-to-content.js
> +    document.getElementById(id).focus();
Sorry, I see you are giving a tab order to the element to allow focus.

2020-09-08 08:30 UTC, rmccar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #852: Skip to main content not working as expected.](https://trello.com/c/Y5NgNiSP/580-issue-852-skip-to-main-content-not-working-as-expected)

2020-09-09 10:03 UTC, jrbarnes9 requested changes
Need to exclude `page__main` from the focus styling. We don't want the border showing.

<img width="745" alt="Screenshot 2020-09-09 at 10 17 38" src="https://user-images.githubusercontent.com/43346934/92584832-09ae9100-f28c-11ea-8efd-e0fe712ea052.png">

2020-09-10 14:38 UTC, jrbarnes9 approved these changes

2020-09-10 14:59 UTC, merged