Increase page__main margin
ONSdigital/design-system pull request #993
Opened 2020-09-16 15:04 UTC by rmccar

### What is the context of this PR?
Fixes: #953 

### How to review 
Check margins above and below page width 740px

2020-09-16 15:04 UTC, rmccar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #953: Increase `page__main` margin-top to 2.5rem (over 740) and 1.5rem (under 740).](https://trello.com/c/mVHxdBNH/644-issue-953-increase-pagemain-margin-top-to-25rem-over-740-and-15rem-under-740)

2020-09-17 11:28 UTC, boxadesign submitted a review, later dismissed

2020-09-17 14:36 UTC, jrbarnes9 requested changes
It looks like this is going to cause a problem for runner.  The problem is we don't specify where breadcrumb navigation should sit in the page template.  Runner adds it's own utility classes to control spacing, and because their 'previous' links are within page__main, they'll be pushed too far down.  We need to rethink this and breadcrumbs...

2020-11-16 08:20 UTC, jrbarnes9 approved these changes

2020-11-16 10:13 UTC, merged